export const names = [
  "Bullock's Oriole",
  "Icterus bullockii",
  "European Starling",
  "Sturnus vulgaris",
  "American Robin",
  "Turdus migratorius",
  "Northern Flicker",
  "Colaptes auratus",
  "House Sparrow",
  "Passer domesticus",
  "House Finch",
  "Haemorhous mexicanus",
  "Bushtit",
  "Psaltriparus minimus",
  "Blue Jay",
  "Cyanocitta cristata",
  "Black-billed Magpie",
  "Pica hudsonia",
  "Savannah Sparrow",
  "Passerculus sandwichensis",
  "White-throated Swift",
  "Aeronautes saxatalis",
  "Great Blue Heron",
  "Ardea herodias",
  "Gray Catbird",
  "Dumetella carolinensis",
  "American Crow",
  "Corvus brachyrhynchos",
  "White-breasted Nuthatch",
  "Sitta carolinensis",
  "Western Tanager",
  "Piranga ludoviciana",
  "Spotted Towhee",
  "Pipilo maculatus",
  "Mourning Dove",
  "Zenaida macroura",
  "Downy Woodpecker",
  "Dryobates pubescens",
  "Cordilleran Flycatcher",
  "Empidonax occidentalis",
  "Band-tailed Pigeon",
  "Patagioenas fasciata",
  "Black-headed Grosbeak",
  "Pheucticus melanocephalus",
  "Western Bluebird",
  "Sialia mexicana",
  "Violet-green Swallow",
  "Tachycineta thalassina",
  "Turkey Vulture",
  "Cathartes aura",
  "Mountain Chickadee",
  "Poecile gambeli",
  "Mountain Bluebird",
  "Sialia currucoides",
  "Lesser Goldfinch",
  "Spinus psaltria",
  "House Wren",
  "Troglodytes aedon",
  "Cooper's Hawk",
  "Accipiter cooperii",
  "Common Poorwill",
  "Phalaenoptilus nuttallii",
  "Chipping Sparrow",
  "Spizella passerina",
  "Blue-gray Gnatcatcher",
  "Polioptila caerulea",
  "Broad-tailed Hummingbird",
  "Selasphorus platycercus",
  "American White Pelican",
  "Pelecanus erythrorhynchos",
  "Yellow-rumped Warbler",
  "Setophaga coronata",
  "Western Meadowlark",
  "Sturnella neglecta",
  "Western Kingbird",
  "Tyrannus verticalis",
  "Vesper Sparrow",
  "Pooecetes gramineus",
  "Red-winged Blackbird",
  "Agelaius phoeniceus",
  "Red-tailed Hawk",
  "Buteo jamaicensis",
  "Grasshopper Sparrow",
  "Ammodramus savannarum",
  "Common Grackle",
  "Quiscalus quiscula",
  "Bobolink",
  "Dolichonyx oryzivorus",
  "Bank Swallow",
  "Riparia riparia",
  "Western Grebe",
  "Aechmophorus occidentalis",
  "Swainson's Hawk",
  "Buteo swainsoni",
  "Osprey",
  "Pandion haliaetus",
  "Mallard",
  "Anas platyrhynchos",
  "Cliff Swallow",
  "Petrochelidon pyrrhonota",
  "Black-capped Chickadee",
  "Poecile atricapillus",
  "Virginia's Warbler",
  "Oreothlypis virginiae",
  "Yellow-breasted Chat",
  "Icteria virens",
  "Barn Swallow",
  "Hirundo rustica",
  "Say's Phoebe",
  "Sayornis saya",
  "Rock Pigeon",
  "Columba livia",
  "Northern Harrier",
  "Circus hudsonius",
  "Killdeer",
  "Charadrius vociferus",
  "Horned Lark",
  "Eremophila alpestris",
  "Great-tailed Grackle",
  "Quiscalus mexicanus",
  "Eurasian Collared-Dove",
  "Streptopelia decaocto",
  "Burrowing Owl",
  "Athene cunicularia",
  "Brown Thrasher",
  "Toxostoma rufum",
  "Canyon Wren",
  "Catherpes mexicanus",
  "Yellow Warbler",
  "Setophaga petechia",
  "Woodhouse's Scrub-Jay",
  "Aphelocoma woodhouseii",
  "Peregrine Falcon",
  "Falco peregrinus",
  "Common Raven",
  "Corvus corax",
  "Canada Goose",
  "Branta canadensis",
  "Double-crested Cormorant",
  "Phalacrocorax auritus",
  "Song Sparrow",
  "Melospiza melodia",
  "Western Wood-Pewee",
  "Contopus sordidulus",
  "Lark Bunting",
  "Calamospiza melanocorys",
  "Swainson's Thrush",
  "Catharus ustulatus",
  "Orchard Oriole",
  "Icterus spurius",
  "Northern Mockingbird",
  "Mimus polyglottos",
  "Lark Sparrow",
  "Chondestes grammacus",
  "American Goldfinch",
  "Spinus tristis",
  "Plumbeous Vireo",
  "Vireo plumbeus",
  "Empidonax sp.",
  "Empidonax sp.",
  "Brown-headed Cowbird",
  "Molothrus ater",
  "Wild Turkey",
  "Meleagris gallopavo",
  "Warbling Vireo",
  "Vireo gilvus",
  "Steller's Jay",
  "Cyanocitta stelleri",
  "swallow sp.",
  "Hirundinidae sp.",
  "Green-tailed Towhee",
  "Pipilo chlorurus",
  "Red-breasted Nuthatch",
  "Sitta canadensis",
  "Pygmy Nuthatch",
  "Sitta pygmaea",
  "Lazuli Bunting",
  "Passerina amoena",
  "American Kestrel",
  "Falco sparverius",
  "Spotted Sandpiper",
  "Actitis macularius",
  "Common Nighthawk",
  "Chordeiles minor",
  "Eastern Kingbird",
  "Tyrannus tyrannus",
  "Bald Eagle",
  "Haliaeetus leucocephalus",
  "American Wigeon",
  "Mareca americana",
  "American Coot",
  "Fulica americana",
  "Gambel's Quail",
  "Callipepla gambelii",
  "Northern Shoveler",
  "Spatula clypeata",
  "Tree Swallow",
  "Tachycineta bicolor",
  "Dark-eyed Junco",
  "Junco hyemalis",
  "Wilson's Warbler",
  "Cardellina pusilla",
  "Ruby-crowned Kinglet",
  "Regulus calendula",
  "Red-naped Sapsucker",
  "Sphyrapicus nuchalis",
  "Hammond's Flycatcher",
  "Empidonax hammondii",
  "Dusky Flycatcher",
  "Empidonax oberholseri",
  "Ash-throated Flycatcher",
  "Myiarchus cinerascens",
  "Sage Thrasher",
  "Oreoscoptes montanus",
  "Black Tern",
  "Chlidonias niger",
  "Yellow-headed Blackbird",
  "Xanthocephalus xanthocephalus",
  "Wilson's Snipe",
  "Gallinago delicata",
  "Pied-billed Grebe",
  "Podilymbus podiceps",
  "Gadwall",
  "Mareca strepera",
  "Common Yellowthroat",
  "Geothlypis trichas",
  "Hairy Woodpecker",
  "Dryobates villosus",
  "Townsend's Solitaire",
  "Myadestes townsendi",
  "Pine Siskin",
  "Spinus pinus",
  "Northern Rough-winged Swallow",
  "Stelgidopteryx serripennis",
  "Black-chinned Hummingbird",
  "Archilochus alexandri",
  "Cedar Waxwing",
  "Bombycilla cedrorum",
  "Willow Flycatcher",
  "Empidonax traillii",
  "Black-capped/Mountain Chickadee",
  "Poecile atricapillus/gambeli",
  "American Dipper",
  "Cinclus mexicanus",
  "Lincoln's Sparrow",
  "Melospiza lincolnii",
  "Evening Grosbeak",
  "Coccothraustes vespertinus",
  "Brewer's Blackbird",
  "Euphagus cyanocephalus",
  "Wilson's Phalarope",
  "Phalaropus tricolor",
  "Ovenbird",
  "Seiurus aurocapilla",
  "Great Horned Owl",
  "Bubo virginianus",
  "Blue Grosbeak",
  "Passerina caerulea",
  "Indigo Bunting",
  "Passerina cyanea",
  "Cattle Egret",
  "Bubulcus ibis",
  "Golden Eagle",
  "Aquila chrysaetos",
  "Orange-crowned Warbler",
  "Oreothlypis celata",
  "Cinnamon Teal",
  "Spatula cyanoptera",
  "American Avocet",
  "Recurvirostra americana",
  "Marsh Wren",
  "Cistothorus palustris",
  "hummingbird sp.",
  "Trochilidae sp.",
  "Green-winged Teal",
  "Anas crecca",
  "Cassin's Finch",
  "Haemorhous cassinii",
  "Blue-winged Teal",
  "Spatula discors",
  "Buteo sp.",
  "Buteo sp.",
  "Black-necked Stilt",
  "Himantopus mexicanus",
  "Black-crowned Night-Heron",
  "Nycticorax nycticorax",
  "California Gull",
  "Larus californicus",
  "Snowy Egret",
  "Egretta thula",
  "Ring-billed Gull",
  "Larus delawarensis",
  "Eared Grebe",
  "Podiceps nigricollis",
  "Clark's Grebe",
  "Aechmophorus clarkii",
  "Belted Kingfisher",
  "Megaceryle alcyon",
  "Wood Duck",
  "Aix sponsa",
  "Rose-breasted Grosbeak",
  "Pheucticus ludovicianus",
  "Common Merganser",
  "Mergus merganser",
  "White-crowned Sparrow",
  "Zonotrichia leucophrys",
  "MacGillivray's Warbler",
  "Geothlypis tolmiei",
  "Greater Roadrunner",
  "Geococcyx californianus",
  "White-faced Ibis",
  "Plegadis chihi",
  "Piping Plover",
  "Charadrius melodus",
  "Mississippi Kite",
  "Ictinia mississippiensis",
  "Loggerhead Shrike",
  "Lanius ludovicianus",
  "Olive-sided Flycatcher",
  "Contopus cooperi",
  "Williamson's Sapsucker",
  "Sphyrapicus thyroideus",
  "Pacific Loon",
  "Gavia pacifica",
  "grackle sp.",
  "Quiscalus sp.",
  "Brewer's Sparrow",
  "Spizella breweri",
  "Sora",
  "Porzana carolina",
  "Hermit Thrush",
  "Catharus guttatus",
  "Rock Wren",
  "Salpinctes obsoletus",
  "Rose-breasted/Black-headed Grosbeak",
  "Pheucticus ludovicianus/melanocephalus",
  "White-winged Dove",
  "Zenaida asiatica",
  "Tree/Violet-green Swallow",
  "Tachycineta bicolor/thalassina",
  "Black-throated Gray Warbler",
  "Setophaga nigrescens",
  "Least Flycatcher",
  "Empidonax minimus",
  "Juniper Titmouse",
  "Baeolophus ridgwayi",
  "Clark's Nutcracker",
  "Nucifraga columbiana",
  "American Bittern",
  "Botaurus lentiginosus",
  "Ruddy Duck",
  "Oxyura jamaicensis",
  "Redhead",
  "Aythya americana",
  "Dickcissel",
  "Spiza americana",
  "Ring-necked Pheasant",
  "Phasianus colchicus",
  "Black-throated Sparrow",
  "Amphispiza bilineata",
  "Gray Vireo",
  "Vireo vicinior",
  "Lewis's Woodpecker",
  "Melanerpes lewis",
  "gull sp.",
  "Larinae sp.",
  "pewee sp. (Contopus sp.)",
  "Contopus sp.",
  "hawk sp.",
  "Accipitridae sp. (hawk sp.)",
  "Canyon Towhee",
  "Melozone fusca",
  "Bewick's Wren",
  "Thryomanes bewickii",
  "Rufous-crowned Sparrow",
  "Aimophila ruficeps",
  "Cassin's Kingbird",
  "Tyrannus vociferans",
  "Northern Goshawk",
  "Accipiter gentilis",
  "Ross's Goose",
  "Anser rossii",
  "Snow Goose",
  "Anser caerulescens",
  "Prairie Falcon",
  "Falco mexicanus",
  "large swift sp.",
  "Apodidae sp. (large swift sp.)",
  "American Three-toed Woodpecker",
  "Picoides dorsalis",
  "blackbird sp.",
  "Icteridae sp.",
  "duck sp.",
  "Anatinae sp.",
  "Chimney Swift",
  "Chaetura pelagica",
  "Eastern Phoebe",
  "Sayornis phoebe",
  "Common Loon",
  "Gavia immer",
  "Pinyon Jay",
  "Gymnorhinus cyanocephalus",
  "Franklin's Gull",
  "Leucophaeus pipixcan",
  "Forster's Tern",
  "Sterna forsteri",
  "Cassin's Sparrow",
  "Peucaea cassinii",
  "Scaled Quail",
  "Callipepla squamata",
  "Red-necked Phalarope",
  "Phalaropus lobatus",
  "Eastern Bluebird",
  "Sialia sialis",
  "Great Egret",
  "Ardea alba",
  "Ring-necked Duck",
  "Aythya collaris",
  "Grace's Warbler",
  "Setophaga graciae",
  "flycatcher sp. (Tyrannidae sp.)",
  "Tyrannidae sp.",
  "American Pipit",
  "Anthus rubescens",
  "Golden-crowned Kinglet",
  "Regulus satrapa",
  "Virginia Rail",
  "Rallus limicola",
  "Common/Forster's Tern",
  "Sterna hirundo/forsteri",
  "Western/Clark's Grebe",
  "Aechmophorus occidentalis/clarkii",
  "Northern Pintail",
  "Anas acuta",
  "Barn Owl",
  "Tyto alba",
  "Catharus sp.",
  "Catharus sp.",
  "owl sp.",
  "Strigiformes sp.",
  "sparrow sp.",
  "Passerellidae sp. (sparrow sp.)",
  "Streptopelia sp.",
  "Streptopelia sp.",
  "crow/raven sp.",
  "Corvus sp.",
  "Red Crossbill",
  "Loxia curvirostra",
  "Mallard (Domestic type)",
  "Anas platyrhynchos (Domestic type)",
  "Red-eyed Vireo",
  "Vireo olivaceus",
  "American Redstart",
  "Setophaga ruticilla",
  "Cassin's/Western Kingbird",
  "Tyrannus vociferans/verticalis",
  "Red-headed Woodpecker",
  "Melanerpes erythrocephalus",
  "Canada Jay",
  "Perisoreus canadensis",
  "Mallard/Mexican Duck",
  "Anas platyrhynchos/diazi",
  "Sandhill Crane",
  "Antigone canadensis",
  "sapsucker sp.",
  "Sphyrapicus sp.",
  "Pine Grosbeak",
  "Pinicola enucleator",
  "Downy/Hairy Woodpecker",
  "Dryobates pubescens/villosus",
  "woodpecker sp.",
  "Picidae sp.",
  "Bullock's/Baltimore Oriole",
  "Icterus bullockii/galbula",
  "Gray Flycatcher",
  "Empidonax wrightii",
  "Fox Sparrow",
  "Passerella iliaca",
  "Hepatic Tanager",
  "Piranga flava",
  "Common Gallinule",
  "Gallinula galeata",
  "Lesser Scaup",
  "Aythya affinis",
  "Ferruginous Hawk",
  "Buteo regalis",
  "shorebird sp.",
  "Charadriiformes sp.",
  "Hooded Merganser",
  "Lophodytes cucullatus",
  "Black Phoebe",
  "Sayornis nigricans",
  "Brown-capped Rosy-Finch",
  "Leucosticte australis",
  "Western/Eastern Wood-Pewee",
  "Contopus sordidulus/virens",
  "Accipiter sp.",
  "Accipiter sp.",
  "Least Sandpiper",
  "Calidris minutilla",
  "Barrow's Goldeneye",
  "Bucephala islandica",
  "White-tailed Ptarmigan",
  "Lagopus leucura",
  "diurnal raptor sp.",
  "Accipitriformes/Falconiformes sp.",
  "Bohemian/Cedar Waxwing",
  "Bombycilla garrulus/cedrorum",
  "Common/Red-breasted Merganser",
  "Mergus merganser/serrator",
  "wren sp.",
  "Troglodytidae sp.",
  "Dusky Grouse",
  "Dendragapus obscurus",
  "Brown Creeper",
  "Certhia americana",
  "Sharp-shinned/Cooper's Hawk",
  "Accipiter striatus/cooperii",
  "Bell's Vireo",
  "Vireo bellii",
  "Green Heron",
  "Butorides virescens",
  "Curve-billed Thrasher",
  "Toxostoma curvirostre",
  "Bufflehead",
  "Bucephala albeola",
  "goose sp.",
  "Anser/Branta sp.",
  "passerine sp.",
  "Passeriformes sp.",
  "Blue-winged/Cinnamon Teal",
  "Spatula discors/cyanoptera",
  "Ladder-backed Woodpecker",
  "Dryobates scalaris",
  "Chihuahuan Raven",
  "Corvus cryptoleucus",
  "Long-billed Curlew",
  "Numenius americanus",
  "Northern Bobwhite",
  "Colinus virginianus",
  "white egret sp.",
  "Ardea/Egretta/Bubulcus sp.",
  "Selasphorus sp.",
  "Selasphorus sp.",
  "Ruby-throated/Black-chinned Hummingbird",
  "Archilochus colubris/alexandri",
  "Semipalmated Sandpiper",
  "Calidris pusilla",
  "Cackling/Canada Goose",
  "Branta hutchinsii/canadensis",
  "Whimbrel",
  "Numenius phaeopus",
  "Hammond's/Dusky Flycatcher",
  "Empidonax hammondii/oberholseri",
  "McCown's Longspur",
  "Rhynchophanes mccownii",
  "Sharp-shinned Hawk",
  "Accipiter striatus",
  "pigeon/dove sp.",
  "Columbidae sp.",
  "Larus sp.",
  "Larus sp.",
  "vireo sp.",
  "Vireo sp.",
  "crossbill sp.",
  "Loxia sp.",
  "Sagebrush Sparrow",
  "Artemisiospiza nevadensis",
  "Northern Parula",
  "Setophaga americana",
  "Summer Tanager",
  "Piranga rubra",
  "Yellow-billed Cuckoo",
  "Coccyzus americanus",
  "Spinus sp. (goldfinch sp.)",
  "Spinus sp. (goldfinch sp.)",
  "warbler sp. (Parulidae sp.)",
  "Parulidae sp.",
  "Graylag Goose (Domestic type)",
  "Anser anser (Domestic type)",
  "large shorebird sp.",
  "Scolopacidae sp. (large shorebird sp.)",
  "Northern Pygmy-Owl",
  "Glaucidium gnoma",
  "Flammulated Owl",
  "Psiloscops flammeolus",
  "phalarope sp.",
  "Phalaropus sp.",
  "Gray/Dusky Flycatcher",
  "Empidonax wrightii/oberholseri",
  "Snowy Plover",
  "Charadrius nivosus",
  "Stilt Sandpiper",
  "Calidris himantopus",
  "Baltimore Oriole",
  "Icterus galbula",
  "Neotropic/Double-crested Cormorant",
  "Phalacrocorax brasilianus/auritus",
  "Domestic goose sp. (Domestic type)",
  "Anser sp. (Domestic type)",
  "Willet",
  "Tringa semipalmata",
  "Field Sparrow",
  "Spizella pusilla",
  "Caspian Tern",
  "Hydroprogne caspia",
  "Glossy/White-faced Ibis",
  "Plegadis falcinellus/chihi",
  "Clay-colored Sparrow",
  "Spizella pallida",
  "Alder/Willow Flycatcher (Traill's Flycatcher)",
  "Empidonax alnorum/traillii",
  "Common Goldeneye",
  "Bucephala clangula",
  "Veery",
  "Catharus fuscescens",
  "Upland Sandpiper",
  "Bartramia longicauda",
  "finch sp.",
  "Fringillidae sp.",
  "Baird's Sparrow",
  "Centronyx bairdii",
  "Western/Eastern Meadowlark",
  "Sturnella neglecta/magna",
  "Chestnut-sided Warbler",
  "Setophaga pensylvanica",
  "Chestnut-collared Longspur",
  "Calcarius ornatus",
  "Eastern Screech-Owl",
  "Megascops asio",
  "Great Crested Flycatcher",
  "Myiarchus crinitus",
  "Haemorhous sp.",
  "Haemorhous sp.",
  "Mountain Plover",
  "Charadrius montanus",
  "Broad-winged Hawk",
  "Buteo platypterus",
  "Spotted/Eastern Towhee (Rufous-sided Towhee)",
  "Pipilo maculatus/erythrophthalmus",
  "Red-bellied Woodpecker",
  "Melanerpes carolinus",
  "Northern Cardinal",
  "Cardinalis cardinalis",
  "small falcon sp.",
  "Falco sp. (small falcon sp.)",
  "raven sp.",
  "Corvus sp. (raven sp.)",
  "Golden/Bald Eagle",
  "Aquila chrysaetos/Haliaeetus leucocephalus",
  "Long-tailed Duck",
  "Clangula hyemalis",
  "Palm Warbler",
  "Setophaga palmarum",
  "Short-billed/Long-billed Dowitcher",
  "Limnodromus griseus/scolopaceus",
  "Lucy's Warbler",
  "Oreothlypis luciae",
  "bluebird sp.",
  "Sialia sp.",
  "Spizella sp./American Tree Sparrow",
  "Spizella/Spizelloides sp.",
  "Black-and-white Warbler",
  "Mniotilta varia",
  "Short-billed Dowitcher",
  "Limnodromus griseus",
  "Blackpoll Warbler",
  "Setophaga striata",
  "Bullock's x Baltimore Oriole (hybrid)",
  "Icterus bullockii x galbula",
  "MacGillivray's/Mourning Warbler",
  "Geothlypis tolmiei/philadelphia",
  "Canvasback",
  "Aythya valisineria",
  "Magnolia Warbler",
  "Setophaga magnolia",
  "Townsend's Warbler",
  "Setophaga townsendi",
  "Acorn Woodpecker",
  "Melanerpes formicivorus",
  "phoebe sp.",
  "Sayornis sp.",
  "nuthatch sp.",
  "Sitta sp.",
  "grebe sp.",
  "Podicipedidae sp.",
  "Setophaga sp.",
  "Setophaga sp.",
  "Greater/Lesser Scaup",
  "Aythya marila/affinis",
  "Spizella sp.",
  "Spizella sp.",
  "Chukar",
  "Alectoris chukar",
  "Mexican Duck",
  "Anas diazi",
  "Vermilion Flycatcher",
  "Pyrocephalus rubinus",
  "Lazuli/Indigo Bunting",
  "Passerina amoena/cyanea",
  "nighthawk sp.",
  "Chordeiles sp.",
  "Carolina Wren",
  "Thryothorus ludovicianus",
  "swift sp.",
  "Apodidae sp.",
  "Scarlet Tanager",
  "Piranga olivacea",
  "Northern Waterthrush",
  "Parkesia noveboracensis",
  "peep sp.",
  "Calidris sp. (peep sp.)",
  "Marbled Godwit",
  "Limosa fedoa",
  "White-rumped Sandpiper",
  "Calidris fuscicollis",
  "Baird's Sandpiper",
  "Calidris bairdii",
  "Painted Bunting",
  "Passerina ciris",
  "Yellow-throated Warbler",
  "Setophaga dominica",
  "dabbling duck sp.",
  "Anatidae sp. (dabbling duck sp.)",
  "Scott's Oriole",
  "Icterus parisorum",
  "Yellow-throated Vireo",
  "Vireo flavifrons",
  "Hooded Warbler",
  "Setophaga citrina",
  "new world oriole sp.",
  "Icterus sp.",
  "yellow-bellied kingbird sp.",
  "Tyrannus sp. (yellow-bellied)",
  "longspur sp.",
  "Calcarius/Rhynchophanes sp.",
  "falcon sp.",
  "Falco sp.",
  "Long-billed Dowitcher",
  "Limnodromus scolopaceus",
  "Graylag Goose (Domestic type) x Canada Goose (hybrid)",
  "Anser anser (Domestic type) x Branta canadensis",
  "Harris's Sparrow",
  "Zonotrichia querula",
  "tern sp.",
  "Sterninae sp.",
  "Eastern Meadowlark",
  "Sturnella magna",
  "Yellow-billed/Black-billed Cuckoo",
  "Coccyzus americanus/erythropthalmus",
  "White-throated Sparrow",
  "Zonotrichia albicollis",
  "Tennessee Warbler",
  "Oreothlypis peregrina",
  "Merlin",
  "Falco columbarius",
  "Graylag x Swan Goose (Domestic type) (hybrid)",
  "Anser anser x cygnoides (Domestic type)",
  "Alder Flycatcher",
  "Empidonax alnorum",
  "Mourning Warbler",
  "Geothlypis philadelphia",
  "Western Screech-Owl",
  "Megascops kennicottii",
  "Greater Yellowlegs",
  "Tringa melanoleuca",
  "Mallard x Mexican Duck (hybrid)",
  "Anas platyrhynchos x diazi",
  "Western Sandpiper",
  "Calidris mauri",
  "Hermit Warbler",
  "Setophaga occidentalis",
  "thrush sp.",
  "Turdidae sp.",
  "Blue-winged x Cinnamon Teal (hybrid)",
  "Spatula discors x cyanoptera",
  "Common Tern",
  "Sterna hirundo",
  "Western x Clark's Grebe (hybrid)",
  "Aechmophorus occidentalis x clarkii",
  "Wood Thrush",
  "Hylocichla mustelina",
  "Tringa sp.",
  "Tringa sp.",
  "jay sp.",
  "Corvidae sp. (jay sp.)",
  "Snow/Ross's Goose",
  "Anser caerulescens/rossii",
  "towhee sp.",
  "Melozone/Pipilo sp.",
  "Lesser Yellowlegs",
  "Tringa flavipes",
  "Rusty/Brewer's Blackbird",
  "Euphagus carolinus/cyanocephalus",
  "Swamp Sparrow",
  "Melospiza georgiana",
  "Lazuli x Indigo Bunting (hybrid)",
  "Passerina amoena x cyanea",
  "Prothonotary Warbler",
  "Protonotaria citrea",
  "Northern Saw-whet Owl",
  "Aegolius acadicus",
  "Sterna sp.",
  "Sterna sp.",
  "Purple Martin",
  "Progne subis",
  "Spotted x Eastern Towhee (hybrid)",
  "Pipilo maculatus x erythrophthalmus",
  "Solitary Sandpiper",
  "Tringa solitaria",
  "Nashville Warbler",
  "Oreothlypis ruficapilla",
  "Bonaparte's Gull",
  "Chroicocephalus philadelphia",
  "Long-eared Owl",
  "Asio otus",
  "rosy-finch sp.",
  "Leucosticte sp.",
  "Semipalmated Plover",
  "Charadrius semipalmatus",
  "Sanderling",
  "Calidris alba",
  "Bay-breasted Warbler",
  "Setophaga castanea",
  "Worm-eating Warbler",
  "Helmitheros vermivorum",
  "Gray-cheeked Thrush",
  "Catharus minimus",
  "Greater/Lesser Yellowlegs",
  "Tringa melanoleuca/flavipes",
  "Lincoln's/Swamp Sparrow",
  "Melospiza lincolnii/georgiana",
  "Greater White-fronted Goose",
  "Anser albifrons",
  "Steller's Jay x Woodhouse's Scrub-Jay (hybrid)",
  "Cyanocitta stelleri x Aphelocoma woodhouseii",
  "Rose-breasted x Black-headed Grosbeak (hybrid)",
  "Pheucticus ludovicianus x melanocephalus",
  "Blue-winged Teal x Northern Shoveler (hybrid)",
  "Spatula discors x clypeata",
  "Red-necked/Red Phalarope",
  "Phalaropus lobatus/fulicarius",
  "Black-bellied Plover",
  "Pluvialis squatarola",
  "Least Tern",
  "Sternula antillarum",
  "Buteo/eagle sp.",
  "Buteo/eagle sp."
];

export const birds = {
  "American Avocet": { iconColor: "fe612d", speciesCode: "ameavo" },
  "Yellow-headed Blackbird": { iconColor: "654d65", speciesCode: "yehbla" },
  "American Coot": { iconColor: "44a61b", speciesCode: "y00475" },
  "Western Kingbird": { iconColor: "eda926", speciesCode: "weskin" },
  "Pied-billed Grebe": { iconColor: "a89d7d", speciesCode: "pibgre" },
  Mallard: { iconColor: "7f6041", speciesCode: "mallar3" },
  "Common Grackle": { iconColor: "784d5", speciesCode: "comgra" },
  "Blue-winged Teal": { iconColor: "b86122", speciesCode: "buwtea" },
  "Blue Jay": { iconColor: "d78f37", speciesCode: "blujay" },
  "Black-necked Stilt": { iconColor: "4b82b5", speciesCode: "bknsti" },
  "American Robin": { iconColor: "c4103d", speciesCode: "amerob" },
  "Western Meadowlark": { iconColor: "871beb", speciesCode: "wesmea" },
  "Red-winged Blackbird": { iconColor: "349bd2", speciesCode: "rewbla" },
  "Red-tailed Hawk": { iconColor: "1dde13", speciesCode: "rethaw" },
  "Northern Shoveler": { iconColor: "956cc6", speciesCode: "norsho" },
  Killdeer: { iconColor: "cc1777", speciesCode: "killde" },
  "House Finch": { iconColor: "cb4598", speciesCode: "houfin" },
  Gadwall: { iconColor: "19a63e", speciesCode: "gadwal" },
  "European Starling": { iconColor: "ed3983", speciesCode: "eursta" },
  "Double-crested Cormorant": { iconColor: "7b1f2a", speciesCode: "doccor" },
  "Cliff Swallow": { iconColor: "2d6ffb", speciesCode: "cliswa" },
  "Cinnamon Teal": { iconColor: "3c466", speciesCode: "cintea" },
  "Canada Goose": { iconColor: "6cb6a6", speciesCode: "cangoo" },
  "Barn Swallow": { iconColor: "9f86b1", speciesCode: "barswa" },
  "American White Pelican": { iconColor: "f0a223", speciesCode: "amwpel" },
  "American Dipper": { iconColor: "455c38", speciesCode: "amedip" },
  "Yellow-rumped Warbler": { iconColor: "baedbd", speciesCode: "yerwar" },
  "Yellow Warbler": { iconColor: "dd4c3", speciesCode: "yelwar" },
  "Wilson's Warbler": { iconColor: "676e25", speciesCode: "wlswar" },
  "Western Tanager": { iconColor: "64eb2d", speciesCode: "westan" },
  "Violet-green Swallow": { iconColor: "4b3e88", speciesCode: "vigswa" },
  "Pine Siskin": { iconColor: "510782", speciesCode: "pinsis" },
  Osprey: { iconColor: "ba9c9e", speciesCode: "osprey" },
  "Northern Rough-winged Swallow": {iconColor: "1964c7", speciesCode: "nrwswa"},
  "Northern Flicker": { iconColor: "6041b1", speciesCode: "norfli" },
  "House Wren": { iconColor: "a3a4d1", speciesCode: "houwre" },
  "Gray Catbird": { iconColor: "edd941", speciesCode: "grycat" },
  "Evening Grosbeak": { iconColor: "f38ebe", speciesCode: "evegro" },
  "Eurasian Collared-Dove": { iconColor: "f08720", speciesCode: "eucdov" },
  "Cordilleran Flycatcher": { iconColor: "90e0f1", speciesCode: "corfly" },
  "Common Merganser": { iconColor: "14c4f1", speciesCode: "commer" },
  "Cedar Waxwing": { iconColor: "21de89", speciesCode: "cedwax" },
  "Bullock's Oriole": { iconColor: "297b86", speciesCode: "bulori" },
  "Broad-tailed Hummingbird": { iconColor: "37441e", speciesCode: "brthum" },
  "Brown-headed Cowbird": { iconColor: "435230", speciesCode: "bnhcow" },
  "Black-capped Chickadee": { iconColor: "95df17", speciesCode: "bkcchi" },
  "American Goldfinch": { iconColor: "8da2cc", speciesCode: "amegfi" },
  "Black-billed Magpie": { iconColor: "b63616", speciesCode: "bkbmag1" },
  "Rock Pigeon": { iconColor: "a001c6", speciesCode: "rocpig" },
  "Hooded Merganser": { iconColor: "440c74", speciesCode: "hoomer" },
  "Great Blue Heron": { iconColor: "98d000", speciesCode: "grbher3" },
  "Lesser Goldfinch": { iconColor: "2796b1", speciesCode: "lesgol" },
  "Chimney Swift": { iconColor: "a463b", speciesCode: "chiswi" },
  "Western Wood-Pewee": { iconColor: "7f52b8", speciesCode: "wewpew" },
  "Mourning Dove": { iconColor: "8dc749", speciesCode: "moudov" },
  "Downy Woodpecker": { iconColor: "edfaf9", speciesCode: "dowwoo" },
  "Woodhouse's Scrub-Jay": { iconColor: "3a0be4", speciesCode: "wooscj2" },
  "White-breasted Nuthatch": { iconColor: "1d0e03", speciesCode: "whbnut" },
  "Warbling Vireo": { iconColor: "12decc", speciesCode: "warvir" },
  "Spotted Towhee": { iconColor: "80365a", speciesCode: "spotow" },
  "Song Sparrow": { iconColor: "d14735", speciesCode: "sonspa" },
  "Brown Thrasher": { iconColor: "ea0a5c", speciesCode: "brnthr" },
  "Red-headed Woodpecker": { iconColor: "a0ad6", speciesCode: "rehwoo" },
  "Orchard Oriole": { iconColor: "eb669b", speciesCode: "orcori" },
  "Eastern Kingbird": { iconColor: "cb030f", speciesCode: "easkin" },
  "Common Nighthawk": { iconColor: "91a062", speciesCode: "comnig" },
  "American Kestrel": { iconColor: "d96796", speciesCode: "amekes" },
  "Savannah Sparrow": { iconColor: "2452d8", speciesCode: "savspa" },
  "Olive-sided Flycatcher": { iconColor: "a50378", speciesCode: "olsfly" },
  Bobolink: { iconColor: "ea0473", speciesCode: "boboli" },
  "American Crow": { iconColor: "f6620e", speciesCode: "amecro" },
  "Western Grebe": { iconColor: "2fefae", speciesCode: "wesgre" },
  "Hairy Woodpecker": { iconColor: "7b6570", speciesCode: "haiwoo" },
  "Black-crowned Night-Heron": { iconColor: "782021", speciesCode: "bcnher" },
  "Spotted Sandpiper": { iconColor: "ace394", speciesCode: "sposan" },
  "Bank Swallow": { iconColor: "d1322b", speciesCode: "banswa" },
  "Western/Eastern Wood-Pewee": { iconColor: "217996", speciesCode: "woopew" },
  "Swainson's Hawk": { iconColor: "eebb7", speciesCode: "swahaw" },
  "Common Yellowthroat": { iconColor: "e8ac46", speciesCode: "comyel" },
  "Black-headed Grosbeak": { iconColor: "405e55", speciesCode: "bkhgro" },
  "White-winged Dove": { iconColor: "55e901", speciesCode: "whwdov" },
  "Mountain Chickadee": { iconColor: "97a3f0", speciesCode: "mouchi" },
  "House Sparrow": { iconColor: "ec77b7", speciesCode: "houspa" },
  "Canyon Towhee": { iconColor: "fb2326", speciesCode: "cantow" },
  "Brewer's Blackbird": { iconColor: "3425b8", speciesCode: "brebla" },
  "Vesper Sparrow": { iconColor: "835d82", speciesCode: "vesspa" },
  "Tree Swallow": { iconColor: "6da97", speciesCode: "treswa" },
  "Snowy Egret": { iconColor: "6a9cc7", speciesCode: "snoegr" },
  "Lark Sparrow": { iconColor: "ac1678", speciesCode: "larspa" },
  "Lark Bunting": { iconColor: "28b211", speciesCode: "larbun" },
  "Horned Lark": { iconColor: "f276b9", speciesCode: "horlar" },
  "Great-tailed Grackle": { iconColor: "a42fd6", speciesCode: "grtgra" },
  "Grasshopper Sparrow": { iconColor: "35def8", speciesCode: "graspa" },
  "Cooper's Hawk": { iconColor: "39aba5", speciesCode: "coohaw" },
  "Forster's Tern": { iconColor: "c1c6fa", speciesCode: "forter" },
  "Wilson's Phalarope": { iconColor: "52d8ed", speciesCode: "wilpha" },
  "Northern Pintail": { iconColor: "8e0a37", speciesCode: "norpin" },
  "Marsh Wren": { iconColor: "5c59d", speciesCode: "marwre" },
  "Green-winged Teal": { iconColor: "4b5349", speciesCode: "gnwtea" },
  "Burrowing Owl": { iconColor: "88910f", speciesCode: "burowl" },
  "Brewer's Sparrow": { iconColor: "98a620", speciesCode: "brespa" },
  "Turkey Vulture": { iconColor: "b86498", speciesCode: "turvul" },
  "Say's Phoebe": { iconColor: "d28069", speciesCode: "saypho" },
  "Green-tailed Towhee": { iconColor: "36df30", speciesCode: "gnttow" },
  "Ferruginous Hawk": { iconColor: "b6bffe", speciesCode: "ferhaw" },
  "Common Raven": { iconColor: "4edac1", speciesCode: "comrav" },
  "Bald Eagle": { iconColor: "a06a24", speciesCode: "baleag" },
  "Red Crossbill": { iconColor: "4e7b28", speciesCode: "redcro" },
  "Dark-eyed Junco": { iconColor: "d7fdb7", speciesCode: "daejun" },
  "White-crowned Sparrow": { iconColor: "a5d5a1", speciesCode: "whcspa" },
  "Ruby-crowned Kinglet": { iconColor: "9f5ba7", speciesCode: "ruckin" },
  "Mountain Bluebird": { iconColor: "dd40a6", speciesCode: "moublu" },
  "swallow sp.": { iconColor: "ae9bc5", speciesCode: "swallo" },
  "Ruddy Duck": { iconColor: "292bcc", speciesCode: "rudduc" },
  "Empidonax sp.": { iconColor: "ba66f", speciesCode: "empido" },
  "Yellow-breasted Chat": { iconColor: "f9aa36", speciesCode: "yebcha" },
  "Lazuli Bunting": { iconColor: "fdcc61", speciesCode: "lazbun" },
  "Golden Eagle": { iconColor: "2ea8b4", speciesCode: "goleag" },
  "Ash-throated Flycatcher": { iconColor: "2e1235", speciesCode: "astfly" },
  "hummingbird sp.": { iconColor: "69ddd0", speciesCode: "hummin" },
  "flycatcher sp. (Tyrannidae sp.)": {iconColor: "7f212", speciesCode: "flycat1"},
  "Black-throated Gray Warbler": { iconColor: "cd4f62", speciesCode: "btywar" },
  "Virginia's Warbler": { iconColor: "ecde8f", speciesCode: "virwar" },
  "Plumbeous Vireo": { iconColor: "93591c", speciesCode: "plsvir" },
  "Dusky Flycatcher": { iconColor: "383218", speciesCode: "dusfly" },
  "Belted Kingfisher": { iconColor: "4e4393", speciesCode: "belkin1" },
  "Black-chinned Hummingbird": { iconColor: "5eb32f", speciesCode: "bkchum" },
  "Clark's Nutcracker": { iconColor: "b83472", speciesCode: "clanut" },
  "Steller's Jay": { iconColor: "1b49bd", speciesCode: "stejay" },
  "Pygmy Nuthatch": { iconColor: "2d3938", speciesCode: "pygnut" },
  "MacGillivray's Warbler": { iconColor: "34ee6", speciesCode: "macwar" },
  "Western Bluebird": { iconColor: "e0198", speciesCode: "wesblu" },
  "Willow Flycatcher": { iconColor: "c23a00", speciesCode: "wilfly" },
  "Lincoln's Sparrow": { iconColor: "cc3fa9", speciesCode: "linspa" },
  "Red-naped Sapsucker": { iconColor: "6f78de", speciesCode: "rensap" },
  "Red-breasted Nuthatch": { iconColor: "6ab007", speciesCode: "rebnut" },
  "White-throated Swift": { iconColor: "13faa0", speciesCode: "whtswi" },
  "Blue Grosbeak": { iconColor: "86d211", speciesCode: "blugrb1" },
  "woodpecker sp.": { iconColor: "5b5391", speciesCode: "woodpe1" },
  "Hepatic Tanager": { iconColor: "2f8211", speciesCode: "heptan" },
  "Northern Mockingbird": { iconColor: "cb272a", speciesCode: "normoc" },
  "Cassin's Kingbird": { iconColor: "44947c", speciesCode: "caskin" },
  "Red-eyed Vireo": { iconColor: "2b9387", speciesCode: "reevir1" },
  "Black-capped/Mountain Chickadee": {iconColor: "7d7cfd", speciesCode: "y00983"},
  "American Redstart": { iconColor: "b3f429", speciesCode: "amered" },
  "Rose-breasted/Black-headed Grosbeak": {iconColor: "e8725b",speciesCode: "y00334"},
  "hawk sp.": { iconColor: "fca3da", speciesCode: "hawk" },
  "Setophaga sp.": { iconColor: "7d994c", speciesCode: "dendro3" },
  "Cassin's Finch": { iconColor: "42afbb", speciesCode: "casfin" },
  "Townsend's Solitaire": { iconColor: "ab7304", speciesCode: "towsol" },
  "Rock Wren": { iconColor: "5a4fb1", speciesCode: "rocwre" },
  "Lewis's Woodpecker": { iconColor: "129e1d", speciesCode: "lewwoo" },
  "Hermit Thrush": { iconColor: "74a292", speciesCode: "herthr" },
  "Chipping Sparrow": { iconColor: "5f080a", speciesCode: "chispa" },
  "Blue-gray Gnatcatcher": { iconColor: "54d352", speciesCode: "buggna" },
  "Wild Turkey": { iconColor: "e20182", speciesCode: "wiltur" },
  "Great Horned Owl": { iconColor: "ed6563", speciesCode: "grhowl" },
  "Wood Duck": { iconColor: "baae86", speciesCode: "wooduc" },
  "Gray Vireo": { iconColor: "7afa53", speciesCode: "gryvir" },
  Bushtit: { iconColor: "40bec2", speciesCode: "bushti" },
  "Wilson's Snipe": { iconColor: "219524", speciesCode: "wilsni1" },
  "Canyon Wren": { iconColor: "a5d446", speciesCode: "canwre" },
  "Clark's Grebe": { iconColor: "ee08f9", speciesCode: "clagre" },
  "Mississippi Kite": { iconColor: "160f6e", speciesCode: "miskit" },
  "Brown Creeper": { iconColor: "a77d72", speciesCode: "brncre" },
  "Hammond's/Dusky Flycatcher": { iconColor: "17eae3", speciesCode: "y00014" },
  Sora: { iconColor: "667e47", speciesCode: "sora" },
  "Scaled Quail": { iconColor: "f14b17", speciesCode: "scaqua" },
  "American Wigeon": { iconColor: "7bb8e6", speciesCode: "amewig" },
  "Gambel's Quail": { iconColor: "ee5a91", speciesCode: "gamqua" },
  "Bewick's Wren": { iconColor: "820cf1", speciesCode: "bewwre" },
  Redhead: { iconColor: "a783d8", speciesCode: "redhea" },
  "Eastern Phoebe": { iconColor: "ef0f54", speciesCode: "easpho" },
  "grackle sp.": { iconColor: "15047e", speciesCode: "grackl" },
  "Black-throated Sparrow": { iconColor: "da3ba7", speciesCode: "bktspa" },
  "Sage Thrasher": { iconColor: "f3b377", speciesCode: "sagthr" },
  "Sharp-shinned/Cooper's Hawk": { iconColor: "52eaac", speciesCode: "y00612" },
  Ovenbird: { iconColor: "f5fbd", speciesCode: "ovenbi1" },
  "Sagebrush Sparrow": { iconColor: "efe6c4", speciesCode: "sagspa1" },
  "Northern Goshawk": { iconColor: "dd9c03", speciesCode: "norgos" },
  "Common Poorwill": { iconColor: "fa2c6a", speciesCode: "compoo" },
  "Northern Pygmy-Owl": { iconColor: "c2340d", speciesCode: "nopowl" },
  "Juniper Titmouse": { iconColor: "141c20", speciesCode: "juntit1" },
  "Peregrine Falcon": { iconColor: "2a1ac9", speciesCode: "perfal" },
  "Prairie Falcon": { iconColor: "65ef10", speciesCode: "prafal" },
  "warbler sp. (Parulidae sp.)": { iconColor: "26d89e", speciesCode: "warble" },
  "Pinyon Jay": { iconColor: "98e9c7", speciesCode: "pinjay" },
  "Tree/Violet-green Swallow": { iconColor: "9c129f", speciesCode: "y00701" },
  "Swainson's Thrush": { iconColor: "d203d4", speciesCode: "swathr" },
  "Band-tailed Pigeon": { iconColor: "c0258a", speciesCode: "batpig1" },
  "Williamson's Sapsucker": { iconColor: "db57aa", speciesCode: "wilsap" },
  "Ring-billed Gull": { iconColor: "ef0b7c", speciesCode: "ribgul" },
  "Greater/Lesser Scaup": { iconColor: "5f4e14", speciesCode: "scaup" },
  "Great Egret": { iconColor: "237eb9", speciesCode: "greegr" },
  "Loggerhead Shrike": { iconColor: "4c97ec", speciesCode: "logshr" },
  "Pacific Loon": { iconColor: "3a3300", speciesCode: "pacloo" },
  "Buteo sp.": { iconColor: "b1fece", speciesCode: "buteo" },
  "Spinus sp. (goldfinch sp.)": { iconColor: "fa6591", speciesCode: "goldfi" },
  "Northern Harrier": { iconColor: "f8ca2c", speciesCode: "norhar2" },
  "Fox Sparrow": { iconColor: "db620c", speciesCode: "foxspa" },
  "Barn Owl": { iconColor: "cfa41b", speciesCode: "brnowl" },
  "Rose-breasted Grosbeak": { iconColor: "4248", speciesCode: "robgro" },
  "Sandhill Crane": { iconColor: "71f0c3", speciesCode: "sancra" },
  "Lesser Scaup": { iconColor: "384a6c", speciesCode: "lessca" },
  "Accipiter sp.": { iconColor: "b149e1", speciesCode: "accipi" },
  "Mallard (Domestic type)": { iconColor: "62bdb3", speciesCode: "mallar2" },
  "Golden-crowned Kinglet": { iconColor: "e35a2b", speciesCode: "gockin" },
  "Hammond's Flycatcher": { iconColor: "8497e7", speciesCode: "hamfly" },
  "Black Tern": { iconColor: "d459c0", speciesCode: "blkter" },
  "Indigo Bunting": { iconColor: "fcd7b6", speciesCode: "indbun" },
  "Orange-crowned Warbler": { iconColor: "cb2884", speciesCode: "orcwar" },
  "California Gull": { iconColor: "75417c", speciesCode: "calgul" },
  "American Pipit": { iconColor: "1e21e1", speciesCode: "amepip" },
  "Cattle Egret": { iconColor: "7e4219", speciesCode: "categr" },
  "Eared Grebe": { iconColor: "4d25ec", speciesCode: "eargre" },
  "Greater Roadrunner": { iconColor: "b32f32", speciesCode: "greroa" },
  "White-faced Ibis": { iconColor: "6065a0", speciesCode: "whfibi" },
  "Piping Plover": { iconColor: "eaaff1", speciesCode: "pipplo" },
  "Gray Flycatcher": { iconColor: "edece3", speciesCode: "gryfly" },
  "American Three-toed Woodpecker": {iconColor: "a0db7a", speciesCode: "attwoo1"},
  "new world oriole sp.": { iconColor: "693f05", speciesCode: "oriole" },
  "wren sp.": { iconColor: "3fe693", speciesCode: "wren1" },
  "Least Flycatcher": { iconColor: "5125e7", speciesCode: "leafly" },
  "Long-eared Owl": { iconColor: "2b248", speciesCode: "loeowl" },
  "American Bittern": { iconColor: "9d6a95", speciesCode: "amebit" },
  Dickcissel: { iconColor: "27c4bb", speciesCode: "dickci" },
  "Ring-necked Pheasant": { iconColor: "aa6bd", speciesCode: "rinphe" },
  "gull sp.": { iconColor: "4d3548", speciesCode: "larus" },
  "pewee sp. (Contopus sp.)": { iconColor: "eda336", speciesCode: "pewee1" },
  Bufflehead: { iconColor: "172e89", speciesCode: "buffle" },
  "duck sp.": { iconColor: "5e94b", speciesCode: "duck1" },
  "Rufous-crowned Sparrow": { iconColor: "99fa86", speciesCode: "rucspa" },
  "Flammulated Owl": { iconColor: "1c9f07", speciesCode: "flaowl" },
  "Mountain Plover": { iconColor: "1de60b", speciesCode: "mouplo" },
  "Ross's Goose": { iconColor: "ae9334", speciesCode: "rosgoo" },
  "Snow Goose": { iconColor: "e6e38d", speciesCode: "snogoo" },
  "large swift sp.": { iconColor: "fab802", speciesCode: "larswi1" },
  "blackbird sp.": { iconColor: "9cb0c0", speciesCode: "blackb" },
  "Common Loon": { iconColor: "11b4e6", speciesCode: "comloo" },
  "Franklin's Gull": { iconColor: "f3d9f2", speciesCode: "fragul" },
  "Cassin's Sparrow": { iconColor: "4f9b99", speciesCode: "casspa" },
  "Red-necked Phalarope": { iconColor: "9de6cb", speciesCode: "renpha" },
  "Eastern Bluebird": { iconColor: "f4dbdf", speciesCode: "easblu" },
  "Ring-necked Duck": { iconColor: "411caa", speciesCode: "rinduc" },
  "Grace's Warbler": { iconColor: "e76a0f", speciesCode: "grawar" },
  "Virginia Rail": { iconColor: "fa28a3", speciesCode: "virrai" },
  "Common/Forster's Tern": { iconColor: "d3a7c2", speciesCode: "y00727" },
  "Catharus sp.": { iconColor: "17f6ca", speciesCode: "cathus" },
  "Chihuahuan Raven": { iconColor: "510b00", speciesCode: "chirav" },
  "owl sp.": { iconColor: "720913", speciesCode: "owl1" },
  "sparrow sp.": { iconColor: "88bc06", speciesCode: "sparro1" },
  "Streptopelia sp.": { iconColor: "832300", speciesCode: "strept1" },
  "crow/raven sp.": { iconColor: "dc469c", speciesCode: "y00639" },
  "Cassin's/Western Kingbird": { iconColor: "6b15a5", speciesCode: "y00619" },
  "Canada Jay": { iconColor: "c58842", speciesCode: "gryjay" },
  "Mallard/Mexican Duck": { iconColor: "341331", speciesCode: "mallar" },
  "sapsucker sp.": { iconColor: "44af09", speciesCode: "sapsuc" },
  "Pine Grosbeak": { iconColor: "bb35e4", speciesCode: "pingro" },
  "Downy/Hairy Woodpecker": { iconColor: "8f48f", speciesCode: "y00322" },
  "Bullock's/Baltimore Oriole": { iconColor: "564dfd", speciesCode: "y00022" },
  "Common Gallinule": { iconColor: "fb51aa", speciesCode: "comgal1" },
  "shorebird sp.": { iconColor: "3982c0", speciesCode: "shoreb1" },
  "Black Phoebe": { iconColor: "6cebe4", speciesCode: "blkpho" },
  "Brown-capped Rosy-Finch": { iconColor: "93c32a", speciesCode: "bcrfin" },
  "Least Sandpiper": { iconColor: "41e807", speciesCode: "leasan" },
  "Barrow's Goldeneye": { iconColor: "5b1aaa", speciesCode: "bargol" },
  "White-tailed Ptarmigan": { iconColor: "58ccec", speciesCode: "whtpta1" },
  "diurnal raptor sp.": { iconColor: "2e4c22", speciesCode: "diurap1" },
  "Bohemian/Cedar Waxwing": { iconColor: "d748bc", speciesCode: "waxwin" },
  "Common/Red-breasted Merganser": {iconColor: "69cf72", speciesCode: "y00224"},
  "Dusky Grouse": { iconColor: "4a0e69", speciesCode: "dusgro" },
  "Black x Eastern Phoebe (hybrid)": {iconColor: "5e5460", speciesCode: "x00621"},
  "Bell's Vireo": { iconColor: "138895", speciesCode: "belvir" },
  "Green Heron": { iconColor: "91cefb", speciesCode: "grnher" },
  "Curve-billed Thrasher": { iconColor: "3db1e1", speciesCode: "cubthr" },
  "goose sp.": { iconColor: "14adeb", speciesCode: "goose1" },
  "passerine sp.": { iconColor: "55bb68", speciesCode: "passer1" },
  "Blue-winged/Cinnamon Teal": { iconColor: "623419", speciesCode: "y00314" },
  "Ladder-backed Woodpecker": { iconColor: "b3effc", speciesCode: "labwoo" },
  "Long-billed Curlew": { iconColor: "adb6be", speciesCode: "lobcur" },
  "Northern Bobwhite": { iconColor: "ffe7c2", speciesCode: "norbob" },
  "Western/Clark's Grebe": { iconColor: "c76858", speciesCode: "y00012" },
  "white egret sp.": { iconColor: "1e7da8", speciesCode: "whiegr1" },
  "Selasphorus sp.": { iconColor: "1a6971", speciesCode: "selasp" },
  "Ruby-throated/Black-chinned Hummingbird": {iconColor: "5daf06", speciesCode: "archil1"},
  "Semipalmated Sandpiper": { iconColor: "f9bf74", speciesCode: "semsan" },
  "Cackling/Canada Goose": { iconColor: "54a94d", speciesCode: "y00470" },
  Whimbrel: { iconColor: "d3ac4a", speciesCode: "whimbr" },
  "Caspian Tern": { iconColor: "473fef", speciesCode: "caster1" },
  "McCown's Longspur": { iconColor: "b34f53", speciesCode: "mcclon" },
  "Sharp-shinned Hawk": { iconColor: "128a8d", speciesCode: "shshaw" },
  "pigeon/dove sp.": { iconColor: "f47535", speciesCode: "dove1" },
  "Larus sp.": { iconColor: "ff0813", speciesCode: "larus1" },
  "vireo sp.": { iconColor: "132140", speciesCode: "vireo1" },
  "crossbill sp.": { iconColor: "181235", speciesCode: "crossb" },
  "Northern Parula": { iconColor: "9397d7", speciesCode: "norpar" },
  "Summer Tanager": { iconColor: "91ced3", speciesCode: "sumtan" },
  "Yellow-billed Cuckoo": { iconColor: "fc2569", speciesCode: "yebcuc" },
  "Graylag Goose (Domestic type)": {iconColor: "684047", speciesCode: "gragoo1"},
  "large shorebird sp.": { iconColor: "2da03d", speciesCode: "larsho1" },
  "phalarope sp.": { iconColor: "340de2", speciesCode: "phalar" },
  "Gray/Dusky Flycatcher": { iconColor: "34c5e", speciesCode: "y00618" },
  "Snowy Plover": { iconColor: "a31488", speciesCode: "snoplo5" },
  "Stilt Sandpiper": { iconColor: "13bdb3", speciesCode: "stisan" },
  "Baltimore Oriole": { iconColor: "7ecb89", speciesCode: "balori" },
  "Neotropic/Double-crested Cormorant": {iconColor: "d2e6b4", speciesCode: "y00833"},
  "Domestic goose sp. (Domestic type)": {iconColor: "f7969d", speciesCode: "domgoo1"},
  Willet: { iconColor: "762134", speciesCode: "willet1" },
  "Field Sparrow": { iconColor: "9bd9ff", speciesCode: "fiespa" },
  "Glossy/White-faced Ibis": { iconColor: "6bd3f6", speciesCode: "plegad" },
  "Clay-colored Sparrow": { iconColor: "17ac67", speciesCode: "clcspa" },
  "Alder/Willow Flycatcher (Traill's Flycatcher)": {iconColor: "8e8501", speciesCode: "y00324"},
  "Common Goldeneye": { iconColor: "8273e9", speciesCode: "comgol" },
  Veery: { iconColor: "a5629c", speciesCode: "veery" },
  "Upland Sandpiper": { iconColor: "26b235", speciesCode: "uplsan" },
  "finch sp.": { iconColor: "8394e1", speciesCode: "finch1" },
  "Baird's Sparrow": { iconColor: "eb07ab", speciesCode: "baispa" },
  "Western/Eastern Meadowlark": { iconColor: "6edd95", speciesCode: "meadow" },
  "Chestnut-sided Warbler": { iconColor: "7b2255", speciesCode: "chswar" },
  "Chestnut-collared Longspur": { iconColor: "767406", speciesCode: "chclon" },
  "Eastern Screech-Owl": { iconColor: "b7614", speciesCode: "easowl1" },
  "Great Crested Flycatcher": { iconColor: "21bcb2", speciesCode: "grcfly" },
  "Haemorhous sp.": { iconColor: "54cf8c", speciesCode: "haemor1" },
  "Broad-winged Hawk": { iconColor: "1c7a2e", speciesCode: "brwhaw" },
  "Spotted/Eastern Towhee (Rufous-sided Towhee)": {iconColor: "6b2f89", speciesCode: "y00226"},
  "Red-bellied Woodpecker": { iconColor: "e262c0", speciesCode: "rebwoo" },
  "Northern Cardinal": { iconColor: "172a39", speciesCode: "norcar" },
  "small falcon sp.": { iconColor: "b812bf", speciesCode: "smafal" },
  "Long-billed Dowitcher": { iconColor: "58a707", speciesCode: "lobdow" },
  "raven sp.": { iconColor: "c68f31", speciesCode: "raven" },
  "Golden/Bald Eagle": { iconColor: "6412d1", speciesCode: "y00944" },
  "Long-tailed Duck": { iconColor: "32517c", speciesCode: "lotduc" },
  "Palm Warbler": { iconColor: "311832", speciesCode: "palwar" },
  "Short-billed/Long-billed Dowitcher": {iconColor: "899aa2", speciesCode: "dowitc"},
  "Lucy's Warbler": { iconColor: "65fa6f", speciesCode: "lucwar" },
  "bluebird sp.": { iconColor: "321919", speciesCode: "bluebi" },
  "Spizella sp./American Tree Sparrow": {iconColor: "c8ddc0", speciesCode: "spizel"},
  "Black-and-white Warbler": { iconColor: "a2c296", speciesCode: "bawwar" },
  "Short-billed Dowitcher": { iconColor: "a86a34", speciesCode: "shbdow" },
  "Blackpoll Warbler": { iconColor: "5e356", speciesCode: "bkpwar" },
  "Bullock's x Baltimore Oriole (hybrid)": {iconColor: "2c982e", speciesCode: "x00013"},
  "MacGillivray's/Mourning Warbler": {iconColor: "4c2868", speciesCode: "y00628"},
  Canvasback: { iconColor: "c5e344", speciesCode: "canvas" },
  "Magnolia Warbler": { iconColor: "3a4de3", speciesCode: "magwar" },
  "Townsend's Warbler": { iconColor: "c4035f", speciesCode: "towwar" },
  "Acorn Woodpecker": { iconColor: "e75fe1", speciesCode: "acowoo" },
  "phoebe sp.": { iconColor: "6e647c", speciesCode: "phoebe1" },
  "nuthatch sp.": { iconColor: "2d3c6f", speciesCode: "nuthat1" },
  "grebe sp.": { iconColor: "3f0138", speciesCode: "grebe1" },
  "Spizella sp.": { iconColor: "2ca6e", speciesCode: "spizel1" },
  Chukar: { iconColor: "4e7db0", speciesCode: "chukar" },
  "Mexican Duck": { iconColor: "f42ba4", speciesCode: "mexduc" },
  "Vermilion Flycatcher": { iconColor: "307bf8", speciesCode: "verfly" },
  "Lazuli/Indigo Bunting": { iconColor: "6c183c", speciesCode: "y00335" },
  "nighthawk sp.": { iconColor: "3b9404", speciesCode: "nighth1" },
  "Carolina Wren": { iconColor: "1ad7ea", speciesCode: "carwre" },
  "swift sp.": { iconColor: "85cde8", speciesCode: "swift1" },
  "Scarlet Tanager": { iconColor: "70b2c1", speciesCode: "scatan" },
  "Northern Waterthrush": { iconColor: "46ad5d", speciesCode: "norwat" },
  "peep sp.": { iconColor: "d789f1", speciesCode: "calidr" },
  "Marbled Godwit": { iconColor: "7a72a7", speciesCode: "margod" },
  "White-rumped Sandpiper": { iconColor: "77189b", speciesCode: "whrsan" },
  "Baird's Sandpiper": { iconColor: "65f0b8", speciesCode: "baisan" },
  "Painted Bunting": { iconColor: "bda864", speciesCode: "paibun" },
  "Yellow-throated Warbler": { iconColor: "429d52", speciesCode: "yetwar" },
  "dabbling duck sp.": { iconColor: "eafdf5", speciesCode: "dabduc1" },
  "Scott's Oriole": { iconColor: "62d457", speciesCode: "scoori" },
  "Yellow-throated Vireo": { iconColor: "da4999", speciesCode: "yetvir" },
  "Hooded Warbler": { iconColor: "43a3a9", speciesCode: "hoowar" },
  "yellow-bellied kingbird sp.": {iconColor: "e4b7a0", speciesCode: "yebkin2"},
  "longspur sp.": { iconColor: "f69ce5", speciesCode: "longsp1" },
  "falcon sp.": { iconColor: "5d04ac", speciesCode: "falcon" },
  "Graylag Goose (Domestic type) x Canada Goose (hybrid)": {iconColor: "a8e0eb", speciesCode: "gragoo4"},
  "Harris's Sparrow": { iconColor: "32be7", speciesCode: "harspa" },
  "tern sp.": { iconColor: "35918f", speciesCode: "tern1" },
  "Eastern Meadowlark": { iconColor: "64e8ee", speciesCode: "easmea" },
  "Yellow-billed/Black-billed Cuckoo": {iconColor: "9f85d6", speciesCode: "y00616"},
  "White-throated Sparrow": { iconColor: "178b57", speciesCode: "whtspa" },
  "Tennessee Warbler": { iconColor: "e8a771", speciesCode: "tenwar" },
  Merlin: { iconColor: "e117fb", speciesCode: "merlin" },
  "Graylag x Swan Goose (Domestic type) (hybrid)": {iconColor: "67faa2", speciesCode: "x00776"},
  "Alder Flycatcher": { iconColor: "ba2da3", speciesCode: "aldfly" },
  "Mourning Warbler": { iconColor: "34c455", speciesCode: "mouwar" },
  "Western Screech-Owl": { iconColor: "d14ccb", speciesCode: "wesowl1" },
  "Greater Yellowlegs": { iconColor: "a612d1", speciesCode: "greyel" },
  "Mallard x Mexican Duck (hybrid)": {iconColor: "e6f852", speciesCode: "mallar4"},
  "Western Sandpiper": { iconColor: "57b79d", speciesCode: "wessan" },
  "Hermit Warbler": { iconColor: "dbbd7f", speciesCode: "herwar" },
  "thrush sp.": { iconColor: "a0bc6f", speciesCode: "thrush1" },
  "Blue-winged x Cinnamon Teal (hybrid)": {iconColor: "996b37", speciesCode: "bwxtea1"},
  "Common Tern": { iconColor: "dcd7fa", speciesCode: "comter" },
  "Western x Clark's Grebe (hybrid)": {iconColor: "457d31", speciesCode: "x00427"},
  "Wood Thrush": { iconColor: "f3b65b", speciesCode: "woothr" },
  "Tringa sp.": { iconColor: "ba9cd7", speciesCode: "tringa1" },
  "jay sp.": { iconColor: "38de52", speciesCode: "jay1" },
  "Snow/Ross's Goose": { iconColor: "448b6b", speciesCode: "y00469" },
  "towhee sp.": { iconColor: "b39cac", speciesCode: "towhee1" },
  "Lesser Yellowlegs": { iconColor: "1aa90f", speciesCode: "lesyel" },
  "Rusty/Brewer's Blackbird": { iconColor: "7d3879", speciesCode: "y00227" },
  "Swamp Sparrow": { iconColor: "31731e", speciesCode: "swaspa" },
  "Lazuli x Indigo Bunting (hybrid)": {iconColor: "880cfd", speciesCode: "ixlbun"},
  "Prothonotary Warbler": { iconColor: "79a829", speciesCode: "prowar" },
  "Northern Saw-whet Owl": { iconColor: "e67db1", speciesCode: "nswowl" },
  "Sterna sp.": { iconColor: "4759b5", speciesCode: "sterna" },
  "Purple Martin": { iconColor: "4d1299", speciesCode: "purmar" },
  "Spotted x Eastern Towhee (hybrid)": {iconColor: "481082", speciesCode: "x00446"},
  "Solitary Sandpiper": { iconColor: "bff59e", speciesCode: "solsan" },
  "Nashville Warbler": { iconColor: "24e273", speciesCode: "naswar" },
  "Bonaparte's Gull": { iconColor: "b0c327", speciesCode: "bongul" },
  "rosy-finch sp.": { iconColor: "126a9a", speciesCode: "rosfin" },
  "Semipalmated Plover": { iconColor: "9eeaef", speciesCode: "semplo" },
  Sanderling: { iconColor: "2c5baf", speciesCode: "sander" },
  "Bay-breasted Warbler": { iconColor: "378b38", speciesCode: "babwar" },
  "Worm-eating Warbler": { iconColor: "8a0ea", speciesCode: "woewar1" },
  "Gray-cheeked Thrush": { iconColor: "df99f0", speciesCode: "gycthr" },
  "Greater/Lesser Yellowlegs": { iconColor: "f4311", speciesCode: "y00476" },
  "Lincoln's/Swamp Sparrow": { iconColor: "67d1f1", speciesCode: "y00688" },
  "Greater White-fronted Goose": { iconColor: "b05291", speciesCode: "gwfgoo" },
  "Steller's Jay x Woodhouse's Scrub-Jay (hybrid)": {iconColor: "320729", speciesCode: "x00891"}
};