export const names = [
  "Bullock's Oriole",
  "Icterus bullockii",
  "European Starling",
  "Sturnus vulgaris",
  "American Robin",
  "Turdus migratorius",
  "Northern Flicker",
  "Colaptes auratus",
  "House Sparrow",
  "Passer domesticus",
  "House Finch",
  "Haemorhous mexicanus",
  "Bushtit",
  "Psaltriparus minimus",
  "Blue Jay",
  "Cyanocitta cristata",
  "Black-billed Magpie",
  "Pica hudsonia",
  "Savannah Sparrow",
  "Passerculus sandwichensis",
  "White-throated Swift",
  "Aeronautes saxatalis",
  "Great Blue Heron",
  "Ardea herodias",
  "Gray Catbird",
  "Dumetella carolinensis",
  "American Crow",
  "Corvus brachyrhynchos",
  "White-breasted Nuthatch",
  "Sitta carolinensis",
  "Western Tanager",
  "Piranga ludoviciana",
  "Spotted Towhee",
  "Pipilo maculatus",
  "Mourning Dove",
  "Zenaida macroura",
  "Downy Woodpecker",
  "Dryobates pubescens",
  "Cordilleran Flycatcher",
  "Empidonax occidentalis",
  "Band-tailed Pigeon",
  "Patagioenas fasciata",
  "Black-headed Grosbeak",
  "Pheucticus melanocephalus",
  "Western Bluebird",
  "Sialia mexicana",
  "Violet-green Swallow",
  "Tachycineta thalassina",
  "Turkey Vulture",
  "Cathartes aura",
  "Mountain Chickadee",
  "Poecile gambeli",
  "Mountain Bluebird",
  "Sialia currucoides",
  "Lesser Goldfinch",
  "Spinus psaltria",
  "House Wren",
  "Troglodytes aedon",
  "Cooper's Hawk",
  "Accipiter cooperii",
  "Common Poorwill",
  "Phalaenoptilus nuttallii",
  "Chipping Sparrow",
  "Spizella passerina",
  "Blue-gray Gnatcatcher",
  "Polioptila caerulea",
  "Broad-tailed Hummingbird",
  "Selasphorus platycercus",
  "American White Pelican",
  "Pelecanus erythrorhynchos",
  "Yellow-rumped Warbler",
  "Setophaga coronata",
  "Western Meadowlark",
  "Sturnella neglecta",
  "Western Kingbird",
  "Tyrannus verticalis",
  "Vesper Sparrow",
  "Pooecetes gramineus",
  "Red-winged Blackbird",
  "Agelaius phoeniceus",
  "Red-tailed Hawk",
  "Buteo jamaicensis",
  "Grasshopper Sparrow",
  "Ammodramus savannarum",
  "Common Grackle",
  "Quiscalus quiscula",
  "Bobolink",
  "Dolichonyx oryzivorus",
  "Bank Swallow",
  "Riparia riparia",
  "Western Grebe",
  "Aechmophorus occidentalis",
  "Swainson's Hawk",
  "Buteo swainsoni",
  "Osprey",
  "Pandion haliaetus",
  "Mallard",
  "Anas platyrhynchos",
  "Cliff Swallow",
  "Petrochelidon pyrrhonota",
  "Black-capped Chickadee",
  "Poecile atricapillus",
  "Virginia's Warbler",
  "Oreothlypis virginiae",
  "Yellow-breasted Chat",
  "Icteria virens",
  "Barn Swallow",
  "Hirundo rustica",
  "Say's Phoebe",
  "Sayornis saya",
  "Rock Pigeon",
  "Columba livia",
  "Northern Harrier",
  "Circus hudsonius",
  "Killdeer",
  "Charadrius vociferus",
  "Horned Lark",
  "Eremophila alpestris",
  "Great-tailed Grackle",
  "Quiscalus mexicanus",
  "Eurasian Collared-Dove",
  "Streptopelia decaocto",
  "Burrowing Owl",
  "Athene cunicularia",
  "Brown Thrasher",
  "Toxostoma rufum",
  "Canyon Wren",
  "Catherpes mexicanus",
  "Yellow Warbler",
  "Setophaga petechia",
  "Woodhouse's Scrub-Jay",
  "Aphelocoma woodhouseii",
  "Peregrine Falcon",
  "Falco peregrinus",
  "Common Raven",
  "Corvus corax",
  "Canada Goose",
  "Branta canadensis",
  "Double-crested Cormorant",
  "Phalacrocorax auritus",
  "Song Sparrow",
  "Melospiza melodia",
  "Western Wood-Pewee",
  "Contopus sordidulus",
  "Lark Bunting",
  "Calamospiza melanocorys",
  "Swainson's Thrush",
  "Catharus ustulatus",
  "Orchard Oriole",
  "Icterus spurius",
  "Northern Mockingbird",
  "Mimus polyglottos",
  "Lark Sparrow",
  "Chondestes grammacus",
  "American Goldfinch",
  "Spinus tristis",
  "Plumbeous Vireo",
  "Vireo plumbeus",
  "Empidonax sp.",
  "Empidonax sp.",
  "Brown-headed Cowbird",
  "Molothrus ater",
  "Wild Turkey",
  "Meleagris gallopavo",
  "Warbling Vireo",
  "Vireo gilvus",
  "Steller's Jay",
  "Cyanocitta stelleri",
  "swallow sp.",
  "Hirundinidae sp.",
  "Green-tailed Towhee",
  "Pipilo chlorurus",
  "Red-breasted Nuthatch",
  "Sitta canadensis",
  "Pygmy Nuthatch",
  "Sitta pygmaea",
  "Lazuli Bunting",
  "Passerina amoena",
  "American Kestrel",
  "Falco sparverius",
  "Spotted Sandpiper",
  "Actitis macularius",
  "Common Nighthawk",
  "Chordeiles minor",
  "Eastern Kingbird",
  "Tyrannus tyrannus",
  "Bald Eagle",
  "Haliaeetus leucocephalus",
  "American Wigeon",
  "Mareca americana",
  "American Coot",
  "Fulica americana",
  "Gambel's Quail",
  "Callipepla gambelii",
  "Northern Shoveler",
  "Spatula clypeata",
  "Tree Swallow",
  "Tachycineta bicolor",
  "Dark-eyed Junco",
  "Junco hyemalis",
  "Wilson's Warbler",
  "Cardellina pusilla",
  "Ruby-crowned Kinglet",
  "Regulus calendula",
  "Red-naped Sapsucker",
  "Sphyrapicus nuchalis",
  "Hammond's Flycatcher",
  "Empidonax hammondii",
  "Dusky Flycatcher",
  "Empidonax oberholseri",
  "Ash-throated Flycatcher",
  "Myiarchus cinerascens",
  "Sage Thrasher",
  "Oreoscoptes montanus",
  "Black Tern",
  "Chlidonias niger",
  "Yellow-headed Blackbird",
  "Xanthocephalus xanthocephalus",
  "Wilson's Snipe",
  "Gallinago delicata",
  "Pied-billed Grebe",
  "Podilymbus podiceps",
  "Gadwall",
  "Mareca strepera",
  "Common Yellowthroat",
  "Geothlypis trichas",
  "Hairy Woodpecker",
  "Dryobates villosus",
  "Townsend's Solitaire",
  "Myadestes townsendi",
  "Pine Siskin",
  "Spinus pinus",
  "Northern Rough-winged Swallow",
  "Stelgidopteryx serripennis",
  "Black-chinned Hummingbird",
  "Archilochus alexandri",
  "Cedar Waxwing",
  "Bombycilla cedrorum",
  "Willow Flycatcher",
  "Empidonax traillii",
  "Black-capped/Mountain Chickadee",
  "Poecile atricapillus/gambeli",
  "American Dipper",
  "Cinclus mexicanus",
  "Lincoln's Sparrow",
  "Melospiza lincolnii",
  "Evening Grosbeak",
  "Coccothraustes vespertinus",
  "Brewer's Blackbird",
  "Euphagus cyanocephalus",
  "Wilson's Phalarope",
  "Phalaropus tricolor",
  "Ovenbird",
  "Seiurus aurocapilla",
  "Great Horned Owl",
  "Bubo virginianus",
  "Blue Grosbeak",
  "Passerina caerulea",
  "Indigo Bunting",
  "Passerina cyanea",
  "Cattle Egret",
  "Bubulcus ibis",
  "Golden Eagle",
  "Aquila chrysaetos",
  "Orange-crowned Warbler",
  "Oreothlypis celata",
  "Cinnamon Teal",
  "Spatula cyanoptera",
  "American Avocet",
  "Recurvirostra americana",
  "Marsh Wren",
  "Cistothorus palustris",
  "hummingbird sp.",
  "Trochilidae sp.",
  "Green-winged Teal",
  "Anas crecca",
  "Cassin's Finch",
  "Haemorhous cassinii",
  "Blue-winged Teal",
  "Spatula discors",
  "Buteo sp.",
  "Buteo sp.",
  "Black-necked Stilt",
  "Himantopus mexicanus",
  "Black-crowned Night-Heron",
  "Nycticorax nycticorax",
  "California Gull",
  "Larus californicus",
  "Snowy Egret",
  "Egretta thula",
  "Ring-billed Gull",
  "Larus delawarensis",
  "Eared Grebe",
  "Podiceps nigricollis",
  "Clark's Grebe",
  "Aechmophorus clarkii",
  "Belted Kingfisher",
  "Megaceryle alcyon",
  "Wood Duck",
  "Aix sponsa",
  "Rose-breasted Grosbeak",
  "Pheucticus ludovicianus",
  "Common Merganser",
  "Mergus merganser",
  "White-crowned Sparrow",
  "Zonotrichia leucophrys",
  "MacGillivray's Warbler",
  "Geothlypis tolmiei",
  "Greater Roadrunner",
  "Geococcyx californianus",
  "White-faced Ibis",
  "Plegadis chihi",
  "Piping Plover",
  "Charadrius melodus",
  "Mississippi Kite",
  "Ictinia mississippiensis",
  "Loggerhead Shrike",
  "Lanius ludovicianus",
  "Olive-sided Flycatcher",
  "Contopus cooperi",
  "Williamson's Sapsucker",
  "Sphyrapicus thyroideus",
  "Pacific Loon",
  "Gavia pacifica",
  "grackle sp.",
  "Quiscalus sp.",
  "Brewer's Sparrow",
  "Spizella breweri",
  "Sora",
  "Porzana carolina",
  "Hermit Thrush",
  "Catharus guttatus",
  "Rock Wren",
  "Salpinctes obsoletus",
  "Rose-breasted/Black-headed Grosbeak",
  "Pheucticus ludovicianus/melanocephalus",
  "White-winged Dove",
  "Zenaida asiatica",
  "Tree/Violet-green Swallow",
  "Tachycineta bicolor/thalassina",
  "Black-throated Gray Warbler",
  "Setophaga nigrescens",
  "Least Flycatcher",
  "Empidonax minimus",
  "Juniper Titmouse",
  "Baeolophus ridgwayi",
  "Clark's Nutcracker",
  "Nucifraga columbiana",
  "American Bittern",
  "Botaurus lentiginosus",
  "Ruddy Duck",
  "Oxyura jamaicensis",
  "Redhead",
  "Aythya americana",
  "Dickcissel",
  "Spiza americana",
  "Ring-necked Pheasant",
  "Phasianus colchicus",
  "Black-throated Sparrow",
  "Amphispiza bilineata",
  "Gray Vireo",
  "Vireo vicinior",
  "Lewis's Woodpecker",
  "Melanerpes lewis",
  "gull sp.",
  "Larinae sp.",
  "pewee sp. (Contopus sp.)",
  "Contopus sp.",
  "hawk sp.",
  "Accipitridae sp. (hawk sp.)",
  "Canyon Towhee",
  "Melozone fusca",
  "Bewick's Wren",
  "Thryomanes bewickii",
  "Rufous-crowned Sparrow",
  "Aimophila ruficeps",
  "Cassin's Kingbird",
  "Tyrannus vociferans",
  "Northern Goshawk",
  "Accipiter gentilis",
  "Ross's Goose",
  "Anser rossii",
  "Snow Goose",
  "Anser caerulescens",
  "Prairie Falcon",
  "Falco mexicanus",
  "large swift sp.",
  "Apodidae sp. (large swift sp.)",
  "American Three-toed Woodpecker",
  "Picoides dorsalis",
  "blackbird sp.",
  "Icteridae sp.",
  "duck sp.",
  "Anatinae sp.",
  "Chimney Swift",
  "Chaetura pelagica",
  "Eastern Phoebe",
  "Sayornis phoebe",
  "Common Loon",
  "Gavia immer",
  "Pinyon Jay",
  "Gymnorhinus cyanocephalus",
  "Franklin's Gull",
  "Leucophaeus pipixcan",
  "Forster's Tern",
  "Sterna forsteri",
  "Cassin's Sparrow",
  "Peucaea cassinii",
  "Scaled Quail",
  "Callipepla squamata",
  "Red-necked Phalarope",
  "Phalaropus lobatus",
  "Eastern Bluebird",
  "Sialia sialis",
  "Great Egret",
  "Ardea alba",
  "Ring-necked Duck",
  "Aythya collaris",
  "Grace's Warbler",
  "Setophaga graciae",
  "flycatcher sp. (Tyrannidae sp.)",
  "Tyrannidae sp.",
  "American Pipit",
  "Anthus rubescens",
  "Golden-crowned Kinglet",
  "Regulus satrapa",
  "Virginia Rail",
  "Rallus limicola",
  "Common/Forster's Tern",
  "Sterna hirundo/forsteri",
  "Western/Clark's Grebe",
  "Aechmophorus occidentalis/clarkii",
  "Northern Pintail",
  "Anas acuta",
  "Barn Owl",
  "Tyto alba",
  "Catharus sp.",
  "Catharus sp.",
  "owl sp.",
  "Strigiformes sp.",
  "sparrow sp.",
  "Passerellidae sp. (sparrow sp.)",
  "Streptopelia sp.",
  "Streptopelia sp.",
  "crow/raven sp.",
  "Corvus sp.",
  "Red Crossbill",
  "Loxia curvirostra",
  "Mallard (Domestic type)",
  "Anas platyrhynchos (Domestic type)",
  "Red-eyed Vireo",
  "Vireo olivaceus",
  "American Redstart",
  "Setophaga ruticilla",
  "Cassin's/Western Kingbird",
  "Tyrannus vociferans/verticalis",
  "Red-headed Woodpecker",
  "Melanerpes erythrocephalus",
  "Canada Jay",
  "Perisoreus canadensis",
  "Mallard/Mexican Duck",
  "Anas platyrhynchos/diazi",
  "Sandhill Crane",
  "Antigone canadensis",
  "sapsucker sp.",
  "Sphyrapicus sp.",
  "Pine Grosbeak",
  "Pinicola enucleator",
  "Downy/Hairy Woodpecker",
  "Dryobates pubescens/villosus",
  "woodpecker sp.",
  "Picidae sp.",
  "Bullock's/Baltimore Oriole",
  "Icterus bullockii/galbula",
  "Gray Flycatcher",
  "Empidonax wrightii",
  "Fox Sparrow",
  "Passerella iliaca",
  "Hepatic Tanager",
  "Piranga flava",
  "Common Gallinule",
  "Gallinula galeata",
  "Lesser Scaup",
  "Aythya affinis",
  "Ferruginous Hawk",
  "Buteo regalis",
  "shorebird sp.",
  "Charadriiformes sp.",
  "Hooded Merganser",
  "Lophodytes cucullatus",
  "Black Phoebe",
  "Sayornis nigricans",
  "Brown-capped Rosy-Finch",
  "Leucosticte australis",
  "Western/Eastern Wood-Pewee",
  "Contopus sordidulus/virens",
  "Accipiter sp.",
  "Accipiter sp.",
  "Least Sandpiper",
  "Calidris minutilla",
  "Barrow's Goldeneye",
  "Bucephala islandica",
  "White-tailed Ptarmigan",
  "Lagopus leucura",
  "diurnal raptor sp.",
  "Accipitriformes/Falconiformes sp.",
  "Bohemian/Cedar Waxwing",
  "Bombycilla garrulus/cedrorum",
  "Common/Red-breasted Merganser",
  "Mergus merganser/serrator",
  "wren sp.",
  "Troglodytidae sp.",
  "Dusky Grouse",
  "Dendragapus obscurus",
  "Brown Creeper",
  "Certhia americana",
  "Sharp-shinned/Cooper's Hawk",
  "Accipiter striatus/cooperii",
  "Bell's Vireo",
  "Vireo bellii",
  "Green Heron",
  "Butorides virescens",
  "Curve-billed Thrasher",
  "Toxostoma curvirostre",
  "Bufflehead",
  "Bucephala albeola",
  "goose sp.",
  "Anser/Branta sp.",
  "passerine sp.",
  "Passeriformes sp.",
  "Blue-winged/Cinnamon Teal",
  "Spatula discors/cyanoptera",
  "Ladder-backed Woodpecker",
  "Dryobates scalaris",
  "Chihuahuan Raven",
  "Corvus cryptoleucus",
  "Long-billed Curlew",
  "Numenius americanus",
  "Northern Bobwhite",
  "Colinus virginianus",
  "white egret sp.",
  "Ardea/Egretta/Bubulcus sp.",
  "Selasphorus sp.",
  "Selasphorus sp.",
  "Ruby-throated/Black-chinned Hummingbird",
  "Archilochus colubris/alexandri",
  "Semipalmated Sandpiper",
  "Calidris pusilla",
  "Cackling/Canada Goose",
  "Branta hutchinsii/canadensis",
  "Whimbrel",
  "Numenius phaeopus",
  "Hammond's/Dusky Flycatcher",
  "Empidonax hammondii/oberholseri",
  "McCown's Longspur",
  "Rhynchophanes mccownii",
  "Sharp-shinned Hawk",
  "Accipiter striatus",
  "pigeon/dove sp.",
  "Columbidae sp.",
  "Larus sp.",
  "Larus sp.",
  "vireo sp.",
  "Vireo sp.",
  "crossbill sp.",
  "Loxia sp.",
  "Sagebrush Sparrow",
  "Artemisiospiza nevadensis",
  "Northern Parula",
  "Setophaga americana",
  "Summer Tanager",
  "Piranga rubra",
  "Yellow-billed Cuckoo",
  "Coccyzus americanus",
  "Spinus sp. (goldfinch sp.)",
  "Spinus sp. (goldfinch sp.)",
  "warbler sp. (Parulidae sp.)",
  "Parulidae sp.",
  "Graylag Goose (Domestic type)",
  "Anser anser (Domestic type)",
  "large shorebird sp.",
  "Scolopacidae sp. (large shorebird sp.)",
  "Northern Pygmy-Owl",
  "Glaucidium gnoma",
  "Flammulated Owl",
  "Psiloscops flammeolus",
  "phalarope sp.",
  "Phalaropus sp.",
  "Gray/Dusky Flycatcher",
  "Empidonax wrightii/oberholseri",
  "Snowy Plover",
  "Charadrius nivosus",
  "Stilt Sandpiper",
  "Calidris himantopus",
  "Baltimore Oriole",
  "Icterus galbula",
  "Neotropic/Double-crested Cormorant",
  "Phalacrocorax brasilianus/auritus",
  "Domestic goose sp. (Domestic type)",
  "Anser sp. (Domestic type)",
  "Willet",
  "Tringa semipalmata",
  "Field Sparrow",
  "Spizella pusilla",
  "Caspian Tern",
  "Hydroprogne caspia",
  "Glossy/White-faced Ibis",
  "Plegadis falcinellus/chihi",
  "Clay-colored Sparrow",
  "Spizella pallida",
  "Alder/Willow Flycatcher (Traill's Flycatcher)",
  "Empidonax alnorum/traillii",
  "Common Goldeneye",
  "Bucephala clangula",
  "Veery",
  "Catharus fuscescens",
  "Upland Sandpiper",
  "Bartramia longicauda",
  "finch sp.",
  "Fringillidae sp.",
  "Baird's Sparrow",
  "Centronyx bairdii",
  "Western/Eastern Meadowlark",
  "Sturnella neglecta/magna",
  "Chestnut-sided Warbler",
  "Setophaga pensylvanica",
  "Chestnut-collared Longspur",
  "Calcarius ornatus",
  "Eastern Screech-Owl",
  "Megascops asio",
  "Great Crested Flycatcher",
  "Myiarchus crinitus",
  "Haemorhous sp.",
  "Haemorhous sp.",
  "Mountain Plover",
  "Charadrius montanus",
  "Broad-winged Hawk",
  "Buteo platypterus",
  "Spotted/Eastern Towhee (Rufous-sided Towhee)",
  "Pipilo maculatus/erythrophthalmus",
  "Red-bellied Woodpecker",
  "Melanerpes carolinus",
  "Northern Cardinal",
  "Cardinalis cardinalis",
  "small falcon sp.",
  "Falco sp. (small falcon sp.)",
  "raven sp.",
  "Corvus sp. (raven sp.)",
  "Golden/Bald Eagle",
  "Aquila chrysaetos/Haliaeetus leucocephalus",
  "Long-tailed Duck",
  "Clangula hyemalis",
  "Palm Warbler",
  "Setophaga palmarum",
  "Short-billed/Long-billed Dowitcher",
  "Limnodromus griseus/scolopaceus",
  "Lucy's Warbler",
  "Oreothlypis luciae",
  "bluebird sp.",
  "Sialia sp.",
  "Spizella sp./American Tree Sparrow",
  "Spizella/Spizelloides sp.",
  "Black-and-white Warbler",
  "Mniotilta varia",
  "Short-billed Dowitcher",
  "Limnodromus griseus",
  "Blackpoll Warbler",
  "Setophaga striata",
  "Bullock's x Baltimore Oriole (hybrid)",
  "Icterus bullockii x galbula",
  "MacGillivray's/Mourning Warbler",
  "Geothlypis tolmiei/philadelphia",
  "Canvasback",
  "Aythya valisineria",
  "Magnolia Warbler",
  "Setophaga magnolia",
  "Townsend's Warbler",
  "Setophaga townsendi",
  "Acorn Woodpecker",
  "Melanerpes formicivorus",
  "phoebe sp.",
  "Sayornis sp.",
  "nuthatch sp.",
  "Sitta sp.",
  "grebe sp.",
  "Podicipedidae sp.",
  "Setophaga sp.",
  "Setophaga sp.",
  "Greater/Lesser Scaup",
  "Aythya marila/affinis",
  "Spizella sp.",
  "Spizella sp.",
  "Chukar",
  "Alectoris chukar",
  "Mexican Duck",
  "Anas diazi",
  "Vermilion Flycatcher",
  "Pyrocephalus rubinus",
  "Lazuli/Indigo Bunting",
  "Passerina amoena/cyanea",
  "nighthawk sp.",
  "Chordeiles sp.",
  "Carolina Wren",
  "Thryothorus ludovicianus",
  "swift sp.",
  "Apodidae sp.",
  "Scarlet Tanager",
  "Piranga olivacea",
  "Northern Waterthrush",
  "Parkesia noveboracensis",
  "peep sp.",
  "Calidris sp. (peep sp.)",
  "Marbled Godwit",
  "Limosa fedoa",
  "White-rumped Sandpiper",
  "Calidris fuscicollis",
  "Baird's Sandpiper",
  "Calidris bairdii",
  "Painted Bunting",
  "Passerina ciris",
  "Yellow-throated Warbler",
  "Setophaga dominica",
  "dabbling duck sp.",
  "Anatidae sp. (dabbling duck sp.)",
  "Scott's Oriole",
  "Icterus parisorum",
  "Yellow-throated Vireo",
  "Vireo flavifrons",
  "Hooded Warbler",
  "Setophaga citrina",
  "new world oriole sp.",
  "Icterus sp.",
  "yellow-bellied kingbird sp.",
  "Tyrannus sp. (yellow-bellied)",
  "longspur sp.",
  "Calcarius/Rhynchophanes sp.",
  "falcon sp.",
  "Falco sp.",
  "Long-billed Dowitcher",
  "Limnodromus scolopaceus",
  "Graylag Goose (Domestic type) x Canada Goose (hybrid)",
  "Anser anser (Domestic type) x Branta canadensis",
  "Harris's Sparrow",
  "Zonotrichia querula",
  "tern sp.",
  "Sterninae sp.",
  "Eastern Meadowlark",
  "Sturnella magna",
  "Yellow-billed/Black-billed Cuckoo",
  "Coccyzus americanus/erythropthalmus",
  "White-throated Sparrow",
  "Zonotrichia albicollis",
  "Tennessee Warbler",
  "Oreothlypis peregrina",
  "Merlin",
  "Falco columbarius",
  "Graylag x Swan Goose (Domestic type) (hybrid)",
  "Anser anser x cygnoides (Domestic type)",
  "Alder Flycatcher",
  "Empidonax alnorum",
  "Mourning Warbler",
  "Geothlypis philadelphia",
  "Western Screech-Owl",
  "Megascops kennicottii",
  "Greater Yellowlegs",
  "Tringa melanoleuca",
  "Mallard x Mexican Duck (hybrid)",
  "Anas platyrhynchos x diazi",
  "Western Sandpiper",
  "Calidris mauri",
  "Hermit Warbler",
  "Setophaga occidentalis",
  "thrush sp.",
  "Turdidae sp.",
  "Blue-winged x Cinnamon Teal (hybrid)",
  "Spatula discors x cyanoptera",
  "Common Tern",
  "Sterna hirundo",
  "Western x Clark's Grebe (hybrid)",
  "Aechmophorus occidentalis x clarkii",
  "Wood Thrush",
  "Hylocichla mustelina",
  "Tringa sp.",
  "Tringa sp.",
  "jay sp.",
  "Corvidae sp. (jay sp.)",
  "Snow/Ross's Goose",
  "Anser caerulescens/rossii",
  "towhee sp.",
  "Melozone/Pipilo sp.",
  "Lesser Yellowlegs",
  "Tringa flavipes",
  "Rusty/Brewer's Blackbird",
  "Euphagus carolinus/cyanocephalus",
  "Swamp Sparrow",
  "Melospiza georgiana",
  "Lazuli x Indigo Bunting (hybrid)",
  "Passerina amoena x cyanea",
  "Prothonotary Warbler",
  "Protonotaria citrea",
  "Northern Saw-whet Owl",
  "Aegolius acadicus",
  "Sterna sp.",
  "Sterna sp.",
  "Purple Martin",
  "Progne subis",
  "Spotted x Eastern Towhee (hybrid)",
  "Pipilo maculatus x erythrophthalmus",
  "Solitary Sandpiper",
  "Tringa solitaria",
  "Nashville Warbler",
  "Oreothlypis ruficapilla",
  "Bonaparte's Gull",
  "Chroicocephalus philadelphia",
  "Long-eared Owl",
  "Asio otus",
  "rosy-finch sp.",
  "Leucosticte sp.",
  "Semipalmated Plover",
  "Charadrius semipalmatus",
  "Sanderling",
  "Calidris alba",
  "Bay-breasted Warbler",
  "Setophaga castanea",
  "Worm-eating Warbler",
  "Helmitheros vermivorum",
  "Gray-cheeked Thrush",
  "Catharus minimus",
  "Greater/Lesser Yellowlegs",
  "Tringa melanoleuca/flavipes",
  "Lincoln's/Swamp Sparrow",
  "Melospiza lincolnii/georgiana",
  "Greater White-fronted Goose",
  "Anser albifrons",
  "Steller's Jay x Woodhouse's Scrub-Jay (hybrid)",
  "Cyanocitta stelleri x Aphelocoma woodhouseii",
  "Rose-breasted x Black-headed Grosbeak (hybrid)",
  "Pheucticus ludovicianus x melanocephalus",
  "Blue-winged Teal x Northern Shoveler (hybrid)",
  "Spatula discors x clypeata",
  "Red-necked/Red Phalarope",
  "Phalaropus lobatus/fulicarius",
  "Black-bellied Plover",
  "Pluvialis squatarola",
  "Least Tern",
  "Sternula antillarum",
  "Buteo/eagle sp.",
  "Buteo/eagle sp."
];

export const iconColors = {
  "Common Nighthawk": "e0f0a5",
  "American Robin": "1c48",
  "House Finch": "8353c8",
  "American White Pelican": "21f423",
  "European Starling": "6776ff",
  "Chimney Swift": "47d321",
  "Spotted Towhee": "c48a43",
  "Bewick's Wren": "b6f42d",
  "Woodhouse's Scrub-Jay": "e164bc",
  "Western Tanager": "a3c8a7",
  "Western Kingbird": "886f35",
  "Western Bluebird": "915692",
  "Violet-green Swallow": "70f274",
  "Red-winged Blackbird": "21f489",
  "Pine Siskin": "10fdf2",
  "Northern Flicker": "7a79c4",
  Mallard: "914329",
  "Juniper Titmouse": "c39385",
  "House Wren": "9c153d",
  "Evening Grosbeak": "75bf9b",
  "Common Raven": "1c1995",
  "Cassin's Finch": "a8211c",
  "Canada Goose": "837585",
  "Bullock's Oriole": "f3a592",
  "Broad-tailed Hummingbird": "dd434",
  "Brewer's Blackbird": "d43e85",
  "Black-headed Grosbeak": "ffaa51",
  "Black-chinned Hummingbird": "4863a2",
  "Black-billed Magpie": "15312f",
  "Downy Woodpecker": "775aa9",
  "Blue Jay": "474922",
  "Western Wood-Pewee": "5aa3aa",
  "Red-tailed Hawk": "474980",
  "Great Horned Owl": "c555c8",
  "Cooper's Hawk": "97a013",
  "Cedar Waxwing": "42bcb5",
  "Tree Swallow": "2375a5",
  Osprey: "60acaf",
  "Western Grebe": "36201a",
  "Common Poorwill": "9eb056",
  "Barn Swallow": "bf06ad",
  "Wild Turkey": "9e4a4e",
  "Mountain Bluebird": "9e681c",
  "Cassin's Kingbird": "618196",
  "Yellow Warbler": "a40dfa",
  "Scaled Quail": "5b4d9c",
  "Mourning Dove": "7039",
  "Lazuli Bunting": "ff40aa",
  "Great Blue Heron": "f2f7f",
  "Eurasian Collared-Dove": "a97f14",
  "Common Grackle": "a116e3",
  "White-throated Swift": "22f864",
  "Hammond's/Dusky Flycatcher": "cf7ea7",
  "American Kestrel": "e4c99",
  "Yellow-rumped Warbler": "93d6b0",
  "Western Meadowlark": "5dcc43",
  "Say's Phoebe": "4994e6",
  "Lincoln's Sparrow": "51208e",
  "Lark Sparrow": "a7654",
  Killdeer: "717d69",
  "Green-tailed Towhee": "759df7",
  "Lesser Goldfinch": "4e5e00",
  "Bald Eagle": "6b37d0",
  "Swainson's Hawk": "806f7a",
  "Song Sparrow": "9bbae4",
  "Black-capped Chickadee": "309f94",
  "White-crowned Sparrow": "1d8861",
  "White-breasted Nuthatch": "312680",
  "Dark-eyed Junco": "8ca0c2",
  "American Crow": "ae3573",
  "Turkey Vulture": "5ff954",
  "Steller's Jay": "841822",
  "Prairie Falcon": "17e5a7",
  "Dusky Flycatcher": "f66d1b",
  "Blue-gray Gnatcatcher": "af2eed",
  "Black-crowned Night-Heron": "ed96c0",
  "warbler sp. (Parulidae sp.)": "2c4dc8",
  "Snowy Egret": "447ddc",
  "Double-crested Cormorant": "a99dde",
  "Belted Kingfisher": "772590",
  "Orchard Oriole": "4ac834",
  "House Sparrow": "ef6772",
  "Eastern Kingbird": "5a1bff",
  "Ash-throated Flycatcher": "95b7",
  "Pinyon Jay": "b3b16d",
  "hummingbird sp.": "c1ea46",
  "Chipping Sparrow": "baae1c",
  "Great-tailed Grackle": "ef73d0",
  "Cordilleran Flycatcher": "d1e53e",
  "Mountain Chickadee": "d8546e",
  "American Goldfinch": "729c54",
  "Wilson's Warbler": "8a2ea9",
  "Tree/Violet-green Swallow": "dee1df",
  "Blue Grosbeak": "93eb6c",
  "Rock Pigeon": "e59030",
  "Cliff Swallow": "b4b40",
  "Brown-headed Cowbird": "8a3962",
  "Olive-sided Flycatcher": "6c97e7",
  "Virginia's Warbler": "c1103b",
  "Pygmy Nuthatch": "8d101b",
  Bobolink: "a7b715",
  "Vesper Sparrow": "eba606",
  "Grasshopper Sparrow": "ae6725",
  "Plumbeous Vireo": "876ecc",
  "Warbling Vireo": "4475c0",
  "Swainson's Thrush": "55cfd4",
  "American Avocet": "d11f6c",
  "Yellow-headed Blackbird": "97ef61",
  "Spotted Sandpiper": "769515",
  "Northern Shoveler": "106bfd",
  "Green-winged Teal": "38e21a",
  "Cinnamon Teal": "32830e",
  "Blue-winged Teal": "11aa2",
  "American Wigeon": "6b0f14",
  "Red-breasted Nuthatch": "7f3c5d",
  "American Coot": "7b4690",
  "Townsend's Solitaire": "6cd1e6",
  Bushtit: "51240c",
  "Canyon Towhee": "371cfd",
  "Burrowing Owl": "11c88b",
  "Horned Lark": "aa4790",
  "Savannah Sparrow": "9c69a9",
  "Forster's Tern": "e5bf54",
  "Great Egret": "8d37ff",
  "Brewer's Sparrow": "37da62",
  "Ruddy Duck": "2b2c86",
  Redhead: "c7ec3a",
  "Loggerhead Shrike": "1a30ab",
  "Gray Catbird": "e7e135",
  "Golden Eagle": "dbc27d",
  Gadwall: "d671ca",
  "Band-tailed Pigeon": "f5e8d6",
  "Pacific Loon": "ac69da",
  "Northern Goshawk": "568c67",
  "Buteo sp.": "f7ddc3",
  "Wood Duck": "b734e1",
  "Northern Rough-winged Swallow": "cbe814",
  "Spinus sp. (goldfinch sp.)": "b66dde",
  "Common Yellowthroat": "f79b50",
  "Bank Swallow": "4b1465",
  "Yellow-breasted Chat": "73b11d",
  "Brown Thrasher": "f30508",
  "Northern Harrier": "98ea33",
  "Canyon Wren": "dd761c",
  "Peregrine Falcon": "79fe13",
  "Empidonax sp.": "d3e1c0",
  "Wilson's Snipe": "e92255",
  "swallow sp.": "ea95c0",
  "Ruby-crowned Kinglet": "512a42",
  "Hairy Woodpecker": "4829bb",
  "Williamson's Sapsucker": "d6b006",
  "Red Crossbill": "f7fa23",
  "Common Merganser": "e08c66",
  "Fox Sparrow": "8d6f32",
  "Barn Owl": "1ec4b2",
  "Rose-breasted Grosbeak": "a66b5",
  "Sandhill Crane": "95acd6",
  "Lark Bunting": "f3b46b",
  "Northern Mockingbird": "4110a4",
  "Red-naped Sapsucker": "46999d",
  "Lesser Scaup": "c6e4f4",
  "Accipiter sp.": "bd8fab",
  "Mallard (Domestic type)": "73a82",
  "American Dipper": "3d8436",
  "Hermit Thrush": "e12e24",
  "Hammond's Flycatcher": "88ce44",
  "Golden-crowned Kinglet": "cd02da",
  "Gambel's Quail": "9554dd",
  "Brown Creeper": "2f27a6",
  "Sage Thrasher": "15c2e1",
  "Black Tern": "12ca7c",
  "Pied-billed Grebe": "a79ad2",
  "Marsh Wren": "f9975f",
  "Indigo Bunting": "4450cf",
  "Willow Flycatcher": "855bb9",
  "Black-throated Gray Warbler": "41afdc",
  "Orange-crowned Warbler": "3d983b",
  "MacGillivray's Warbler": "d78e4e",
  "Black-capped/Mountain Chickadee": "1790c7",
  "American Pipit": "d917c7",
  "Wilson's Phalarope": "f441d7",
  Ovenbird: "dd80d9",
  "Cattle Egret": "d5f68d",
  "Sagebrush Sparrow": "9aa70e",
  "Black-necked Stilt": "301942",
  "California Gull": "b44edf",
  "Ring-billed Gull": "40d251",
  "Eared Grebe": "bcb631",
  "Clark's Grebe": "c3d711",
  "Greater Roadrunner": "6fa90",
  "White-faced Ibis": "d7d6f3",
  "Piping Plover": "def793",
  "Mississippi Kite": "859d3c",
  "flycatcher sp. (Tyrannidae sp.)": "698105",
  "Clark's Nutcracker": "9a982c",
  "grackle sp.": "4fc47d",
  "Black-throated Sparrow": "52eff0",
  "Rock Wren": "bc4e64",
  "Gray Vireo": "a3cb8d",
  "Gray Flycatcher": "a22192",
  "Sharp-shinned/Cooper's Hawk": "5becfa",
  "American Three-toed Woodpecker": "4b2795",
  Sora: "a8e31a",
  "Rose-breasted/Black-headed Grosbeak": "447357",
  "new world oriole sp.": "4e9fdc",
  "White-winged Dove": "63b8e0",
  "Least Flycatcher": "5873f8",
  "American Bittern": "6ecf4",
  Dickcissel: "c95a8",
  "Ring-necked Pheasant": "2f38ee",
  "Lewis's Woodpecker": "48433a",
  "gull sp.": "237b96",
  "pewee sp. (Contopus sp.)": "a09104",
  Bufflehead: "b1f6f",
  "hawk sp.": "50d3e3",
  "duck sp.": "fbbc78",
  "Rufous-crowned Sparrow": "3a9eca",
  "Flammulated Owl": "b06628",
  "Northern Pygmy-Owl": "691d79",
  "Mountain Plover": "7367d6",
  "Ross's Goose": "396880",
  "Snow Goose": "ad3bad",
  "large swift sp.": "cb13cb",
  "blackbird sp.": "36b78a",
  "Eastern Phoebe": "d7d949",
  "Common Loon": "a314ad",
  "Franklin's Gull": "24b200",
  "Cassin's Sparrow": "de1c11",
  "Red-necked Phalarope": "b6a40f",
  "Eastern Bluebird": "4530e2",
  "Ring-necked Duck": "aec9fa",
  "Grace's Warbler": "df4ab9",
  "Virginia Rail": "d0dc0",
  "Common/Forster's Tern": "d23367",
  "Western/Clark's Grebe": "318bd",
  "Northern Pintail": "86e120",
  "Catharus sp.": "8fb42d",
  "Chihuahuan Raven": "93e8ae",
  "owl sp.": "7d8344",
  "sparrow sp.": "36d6ad",
  "Streptopelia sp.": "ab696",
  "crow/raven sp.": "49839c",
  "Red-eyed Vireo": "bda303",
  "American Redstart": "9a2a5e",
  "Cassin's/Western Kingbird": "3d4625",
  "Red-headed Woodpecker": "f415e7",
  "Canada Jay": "d4ff75",
  "Mallard/Mexican Duck": "387edd",
  "sapsucker sp.": "24e433",
  "Pine Grosbeak": "3876ce",
  "Downy/Hairy Woodpecker": "dcaf4c",
  "woodpecker sp.": "972aec",
  "Bullock's/Baltimore Oriole": "62cbd9",
  "Hepatic Tanager": "7be3",
  "Common Gallinule": "a89ebc",
  "Ferruginous Hawk": "face0d",
  "shorebird sp.": "8ee823",
  "Hooded Merganser": "e5aae4",
  "Black Phoebe": "3fbea4",
  "Brown-capped Rosy-Finch": "e6957d",
  "Western/Eastern Wood-Pewee": "3eb843",
  "Least Sandpiper": "75e314",
  "Barrow's Goldeneye": "a01769",
  "White-tailed Ptarmigan": "857f32",
  "diurnal raptor sp.": "a6d4a8",
  "Bohemian/Cedar Waxwing": "d0ea4d",
  "Common/Red-breasted Merganser": "b46e02",
  "wren sp.": "3f2e4",
  "Dusky Grouse": "623905",
  "Black x Eastern Phoebe (hybrid)": "192136",
  "Bell's Vireo": "450682",
  "Green Heron": "322c82",
  "Curve-billed Thrasher": "8e4871",
  "goose sp.": "9202bd",
  "passerine sp.": "73aa4",
  "Blue-winged/Cinnamon Teal": "299d8f",
  "Ladder-backed Woodpecker": "139df2",
  "Long-billed Curlew": "122b0e",
  "Northern Bobwhite": "396b40",
  "white egret sp.": "712942",
  "Selasphorus sp.": "c689d4",
  "Ruby-throated/Black-chinned Hummingbird": "bd7e4d",
  "Semipalmated Sandpiper": "bc7128",
  "Cackling/Canada Goose": "c44282",
  Whimbrel: "a0726",
  "McCown's Longspur": "6dd2a0",
  "Sharp-shinned Hawk": "e7bb66",
  "pigeon/dove sp.": "294dcd",
  "Larus sp.": "da0863",
  "vireo sp.": "3ea405",
  "crossbill sp.": "43e55",
  "Northern Parula": "917b50",
  "Summer Tanager": "be00b9",
  "Yellow-billed Cuckoo": "a6b226",
  "Graylag Goose (Domestic type)": "afe476",
  "large shorebird sp.": "5113d8",
  "phalarope sp.": "176eed",
  "Gray/Dusky Flycatcher": "3deb6c",
  "Snowy Plover": "252e4",
  "Stilt Sandpiper": "d78d1e",
  "Baltimore Oriole": "b1f61c",
  "Neotropic/Double-crested Cormorant": "96574",
  "Domestic goose sp. (Domestic type)": "cc1484",
  Willet: "7bcc19",
  "Field Sparrow": "7566a7",
  "Caspian Tern": "bfa6aa",
  "Glossy/White-faced Ibis": "274f25",
  "Clay-colored Sparrow": "711e09",
  "Alder/Willow Flycatcher (Traill's Flycatcher)": "61e94e",
  "Common Goldeneye": "d3b912",
  Veery: "78c72e",
  "Upland Sandpiper": "66b2ab",
  "finch sp.": "beceec",
  "Baird's Sparrow": "1ecb49",
  "Western/Eastern Meadowlark": "51902b",
  "Chestnut-sided Warbler": "b290e",
  "Chestnut-collared Longspur": "2257f0",
  "Eastern Screech-Owl": "57ad94",
  "Great Crested Flycatcher": "a40d12",
  "Haemorhous sp.": "c69d45",
  "Broad-winged Hawk": "992495",
  "Spotted/Eastern Towhee (Rufous-sided Towhee)": "2be3e",
  "Red-bellied Woodpecker": "ea53f1",
  "Northern Cardinal": "29d415",
  "small falcon sp.": "3f2817",
  "raven sp.": "d310b4",
  "Golden/Bald Eagle": "3483f9",
  "Long-tailed Duck": "f4baed",
  "Palm Warbler": "3699fb",
  "Short-billed/Long-billed Dowitcher": "377ce3",
  "Lucy's Warbler": "e59620",
  "bluebird sp.": "b2815a",
  "Spizella sp./American Tree Sparrow": "4ce18",
  "Black-and-white Warbler": "748973",
  "Short-billed Dowitcher": "369958",
  "Blackpoll Warbler": "d4dfc2",
  "Bullock's x Baltimore Oriole (hybrid)": "1f08bd",
  "MacGillivray's/Mourning Warbler": "d6319b",
  Canvasback: "976a7c",
  "Magnolia Warbler": "d29b2",
  "Townsend's Warbler": "48307f",
  "Acorn Woodpecker": "2bfc46",
  "phoebe sp.": "108bf0",
  "nuthatch sp.": "e700e4",
  "grebe sp.": "984cac",
  "Setophaga sp.": "8da56",
  "Greater/Lesser Scaup": "c1f183",
  "Spizella sp.": "96316a",
  Chukar: "74bc33",
  "Mexican Duck": "fd062b",
  "Vermilion Flycatcher": "76484d",
  "Lazuli/Indigo Bunting": "5bcb61",
  "nighthawk sp.": "1cfbe0",
  "Carolina Wren": "65ccd5",
  "swift sp.": "897e17",
  "Scarlet Tanager": "1e5b6b",
  "Northern Waterthrush": "57a47f",
  "peep sp.": "37c888",
  "Marbled Godwit": "a298b6",
  "White-rumped Sandpiper": "6a0695",
  "Baird's Sandpiper": "3ea40f",
  "Painted Bunting": "ebedca",
  "Yellow-throated Warbler": "8413a6",
  "dabbling duck sp.": "8ad71d",
  "Scott's Oriole": "74df5a",
  "Yellow-throated Vireo": "21097b",
  "Hooded Warbler": "b66c2b",
  "yellow-bellied kingbird sp.": "ef80c4",
  "longspur sp.": "307f9a",
  "falcon sp.": "a8e1b0",
  "Long-billed Dowitcher": "b3cc1d",
  "Graylag Goose (Domestic type) x Canada Goose (hybrid)": "b08558",
  "Harris's Sparrow": "d1ca4c",
  "tern sp.": "1e104",
  "Eastern Meadowlark": "476b46",
  "Yellow-billed/Black-billed Cuckoo": "c4e7e0",
  "White-throated Sparrow": "64bfad",
  "Tennessee Warbler": "a7d969",
  Merlin: "48b120",
  "Graylag x Swan Goose (Domestic type) (hybrid)": "f9a305",
  "Alder Flycatcher": "570041",
  "Mourning Warbler": "36f4f4",
  "Western Screech-Owl": "b3da02",
  "Greater Yellowlegs": "5e301d",
  "Mallard x Mexican Duck (hybrid)": "4ec4b8",
  "Western Sandpiper": "ef53a5",
  "Hermit Warbler": "9edab1",
  "thrush sp.": "111d16",
  "Blue-winged x Cinnamon Teal (hybrid)": "85680f",
  "Common Tern": "74d8b7",
  "Western x Clark's Grebe (hybrid)": "f7845",
  "Wood Thrush": "ccaa9c",
  "Tringa sp.": "b96df0",
  "jay sp.": "9c74a7",
  "Snow/Ross's Goose": "b697ca",
  "towhee sp.": "577b54",
  "Lesser Yellowlegs": "3de869",
  "Rusty/Brewer's Blackbird": "a176ae",
  "Swamp Sparrow": "d036ed",
  "Lazuli x Indigo Bunting (hybrid)": "a11d02",
  "Prothonotary Warbler": "743947",
  "Northern Saw-whet Owl": "ad5e66",
  "Sterna sp.": "ee138b",
  "Purple Martin": "874ef3",
  "Spotted x Eastern Towhee (hybrid)": "95f739",
  "Solitary Sandpiper": "1d4bac",
  "Nashville Warbler": "a435d5",
  "Bonaparte's Gull": "d15bbf",
  "Long-eared Owl": "cd5d76",
  "rosy-finch sp.": "1aa00d",
  "Semipalmated Plover": "a7759e",
  Sanderling: "540f0d",
  "Bay-breasted Warbler": "f50ea1",
  "Worm-eating Warbler": "d9eab8",
  "Gray-cheeked Thrush": "55833a",
  "Greater/Lesser Yellowlegs": "8d1219",
  "Lincoln's/Swamp Sparrow": "7bc040",
  "Greater White-fronted Goose": "735d76",
  "Steller's Jay x Woodhouse's Scrub-Jay (hybrid)": "fb6040",
  "Rose-breasted x Black-headed Grosbeak (hybrid)": "f62d",
  "Blue-winged Teal x Northern Shoveler (hybrid)": "d87b7",
  "Red-necked/Red Phalarope": "15cdc2",
  "Black-bellied Plover": "345446",
  "Least Tern": "ea0216",
  "Buteo/eagle sp.": "57bf36"
};